### ISSUE TITLE
Error: #<Bosh::Clouds::CloudError: Invalid data disk name (version 1) -- in disk attach -- in Azure

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry/bosh#1841] opened 2017-11-24 13:50 UTC
But when I manually attach .....no problem..and happening on Azure.

**command**: 
bosh -e bosh-my-env -d my-deployment-name attach-disk blueprint_z1/06457717-5e63-4d1a-94d0-671fb59cdd4e  my-disk-25917-2017112412334

**output**:
 Error: CPI error 'Bosh::Clouds::CloudError' with message 'attach_disk - Failed to create the managed disk for my-disk-25917-20171124123341. Error: #<Bosh::Clouds::CloudError: Invalid data disk name (version 1) my-disk-25917-20171124123341

/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/helpers.rb:163:in `cloud_error'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_id.rb:133:in `parse_storage_account_v1'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_id.rb:101:in `storage_account_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:384:in `block in attach_disk'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:371:in `attach_disk'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `load'
/var/vcap/packages/ruby_azure_cpi/bin/bundle:23:in `<main>'' in 'attach_disk' CPI method

**Comment by cppforlife** [comment] 2017-11-24 15:29
@sauravmndl what i suspect is that cpi expects to have disks with particular names. may be @AbelHu has an idea how to support what you are trying to do? (i assume its some disks that you have to recover)

**Comment by AbelHu** [comment] 2017-11-25 13:32
Azure has naming rules for disk name. Please see the rules [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/disk_id.rb).

**Comment by sauravmndl** [comment] 2017-11-27 12:34
@AbelHu  and @cppforlife Thank you very much for your help so far. I have given a acceptable name () in attach command, but giving me following error now 

` DirectorJobRunner: CPI error 'Bosh::Clouds::CloudError' with message 'Unknown disk caching xxxxxxxxxx' in 'attach_disk' CPI method
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:195:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:99:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/cloud/external_cpi.rb:61:in `attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/disk_manager.rb:76:in `attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:78:in `handle_new_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:31:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:136:in `_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:110:in `block in transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:99:in `transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:5:in `block in retryable_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/common.rb:118:in `retryable'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:4:in `retryable_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:29:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:96:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:85:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-11-27 12:17:42 #5561] [task:820] DEBUG -- DirectorJobRunner: (0.000084s) SELECT NULL
D, [2017-11-27 12:17:42 #5561] [task:820] DEBUG -- DirectorJobRunner: (0.000194s) SELECT * FROM "tasks" WHERE ("id" = 820) LIMIT 1
D, [2017-11-27 12:17:42 #5561] [task:820] DEBUG -- DirectorJobRunner: (0.000122s) SELECT NULL
D, [2017-11-27 12:17:42 #5561] [task:820] DEBUG -- DirectorJobRunner: (0.000053s) BEGIN`

**Comment by AbelHu** [comment] 2017-11-28 01:33
@sauravmndl It seems like that you used an invalid caching `xxxxxxxxxx`. Please see the code [here](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/1257c994ec21ae427849e04899fcdee89c664ba8/src/bosh_azure_cpi/lib/cloud/azure/helpers.rb#L177-L181).
valid_caching = ['None', 'ReadOnly', 'ReadWrite']

**Comment by sauravmndl** [comment] 2017-11-28 05:20
Hi @AbelHu , thanks for the help. Now I have found the correct command. Bosh cli is accepting the command but throwing following error saying volume not found. But it is actually present in Azure. Following is the error detail. 

`[2017-11-27 18:33:11 #13053] [task:869] ERROR -- DirectorJobRunner: Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id 'disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1' could not be found
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:301:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:356:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:58:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:412:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:206:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:376:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:106:in `mount_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/disk_manager.rb:169:in `mount_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/disk_manager.rb:78:in `attach_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:78:in `handle_new_disk'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:31:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:136:in `_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:110:in `block in transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:99:in `transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:5:in `block in retryable_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/common.rb:118:in `retryable'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/transactor.rb:4:in `retryable_transaction'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/attach_disk.rb:29:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:96:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:85:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000094s) SELECT NULL
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000237s) SELECT * FROM "tasks" WHERE ("id" = 869) LIMIT 1
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000133s) SELECT NULL
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000063s) BEGIN
D, [2017-11-27 18:33:11 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.000414s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-11-27 18:33:11.981151+0000', "description" = 'attach disk ''disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1'' to ''blueprint_z1/c6df4272-3efc-44ee-a186-ce8101fb12db''', "result" = 'Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id...', "output" = '/var/vcap/store/director/tasks/869', "checkpoint_time" = '2017-11-27 18:32:47.015496+0000', "type" = 'attach_disk', "username" = 'admin', "deployment_name" = 'service-fabrik-1047-a8ff8ce0-9577-4506-be04-3483ddd2f2f2', "started_at" = '2017-11-27 18:30:46.968654+0000', "event_output" = '{"time":1511807591,"error":{"code":450001,"message":"Action Failed get_task: Task b5b3835f-b379-44c0-6f25-9ad693e5be0d result: Persistent disk with volume id ''disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sf-azure-dev1'' could not be found"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 869)
D, [2017-11-27 18:33:12 #13053] [task:869] DEBUG -- DirectorJobRunner: (0.025650s) COMMIT
I, [2017-11-27 18:33:12 #13053] []  INFO -- DirectorJobRunner: Task took 2 minutes 25.041717989999995 seconds to process.

Task 869 error

Capturing task '869' output:
  Expected task '869' to succeed but state is 'error'

Exit code 1`

**Comment by AbelHu** [comment] 2017-11-28 05:27
@sauravmndl From the disk name `disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;caching:None;resource_group_name:rg-sample-azure-dev1` in your latest logs, it shows that you are using **managed disks** in V2 format. If so, you should be able to find the managed disk `bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae` under the resource group `rg-sample-azure-dev1` in [Azure portal](https://ms.portal.azure.com/). Please confirm it at first.

**Comment by sauravmndl** [comment] 2017-11-28 05:52
@AbelHu  I am confirming again that the disk is present in the resource group.

**Comment by AbelHu** [comment] 2017-11-28 06:01
@sauravmndl It seems like that Azure CPI has attached this disk to the VM (I think you can double confirm this in Azure portal) and the error was thrown by bosh-agent. I suggest you to login to the VM, check attached disks by `lsblk` and check the disks' information in `/var/vcap/bosh/settings.json`.

**Comment by sauravmndl** [comment] 2017-11-28 07:06
@AbelHu 
I can see the disks section of /var/vcap/bosh/setings.json contains following  but `sdd` is not included in `lsblk` command

` "disks": {                                                                                                                 
   "raw_ephemeral": null,                                                                                                   
   "persistent": {                                                                                                          
     "caching:None;disk_name:bosh-disk-data-0a8f47bc-e934-4a7f-90c5-ec775d5b71ae;resource_group_name:rg-sample-azure-dev1": {   
       "path": "/dev/sdd",                                                                                                  
       "lun": "1",                                                                                                          
       "host_device_id": "{f8b3781b-1e82-4818-a1c3-63d806ec15bb}"                                                           
     }                                                                                                                      
   },                                                                                                                       
   "ephemeral": {                                                                                                           
     "path": "/dev/sdc",                                                                                                    
     "lun": "0",                                                                                                            
     "host_device_id": "{f8b3781b-1e82-4818-a1c3-63d806ec15bb}"                                                             
   },                                                                                                                       
   "system": "/dev/sda"                                                                                                     
 },                                                                                                                         `

**Comment by AbelHu** [comment] 2017-11-28 07:17
@sauravmndl From `/var/vcap/bosh/setings.json`, it seems like that Azure CPI did have attached the data disk successfully.
1. Did you check whether the disk is attached to the VM in Azure portal?
2. Could you see sdd by `sudo fdisk -l` inside the VM?

If both are yes, maybe bosh-agent failed to format the new disk. You should be able to find some errors in bosh-agent's logs `/var/vcap/bosh/log/*` inside the VM.

**Comment by sauravmndl** [comment] 2017-11-28 08:19
@AbelHu  Did you check whether the disk is attached to the VM in Azure portal? ===> Not attached
Could you see sdd by sudo fdisk -l inside the VM? ==> sdd is not listed

I have observed the behaviour: The disk gets attached for some moment and doesn't get mounted. Then detached. Then shows the error --> volume not found.

**Comment by sauravmndl** [comment] 2017-11-28 08:38
I see the issue is to some extent similar to https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/227 

 The vm type I am using is: D2S_V3
And bosh stemcell is : bosh-azure-hyperv-ubuntu-trusty-go_agent  3468

**Comment by AbelHu** [comment] 2017-11-29 01:15
@sauravmndl It seems like to be an infrastructure issue. I suggest you to file a support ticket with the log of the task to attach the disk in Azure portal.

**Comment by sauravmndl** [comment] 2017-11-29 13:13
@AbelHu  Thanks for  the help above. Will create a support request.

**Comment by sauravmndl** [comment] 2017-12-08 13:43
Reopening it as seems to be bosh issue. Creating a ticket also and will update here.

**Comment by sauravmndl** [comment] 2017-12-08 13:43
Same as https://github.com/cloudfoundry/bosh/issues/1857

**Comment by dpb587-pivotal** [comment] 2017-12-21 07:03
Closing as duplicate of resolved #1857.

**Closed by dpb587-pivotal** 2017-12-21 07:03 UTC
Labels: discuss
