### ISSUE TITLE
auditd does not start

### ISSUE THREAD

**Issue by rfreddi** [cloudfoundry/bosh#1305] opened 2016-06-16 18:50 UTC
Hi, the auditd service does not start on stemcell based on 3232.4 and 3232.6 image.

bash -x service auditd start
    ++ basename service
    VERSION='service ver. 0.91-ubuntu1' ++ basename service
    USAGE='Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]'
    SERVICE=
    ACTION=
    SERVICEDIR=/etc/init.d
    OPTIONS=
    '[' 2 -eq 0 ']'
    cd /
    '[' 2 -gt 0 ']'
    case "${1}" in
    '[' -z '' -a 2 -eq 1 -a auditd = --status-all ']'
    '[' 2 -eq 2 -a start = --full-restart ']'
    '[' -z '' ']'
    SERVICE=auditd
    shift
    '[' 1 -gt 0 ']'
    case "${1}" in
    '[' -z auditd -a 1 -eq 1 -a start = --status-all ']'
    '[' 1 -eq 2 -a '' = --full-restart ']'
    '[' -z auditd ']'
    '[' -z '' ']'
    ACTION=start
    shift
    '[' 0 -gt 0 ']'
    '[' -r /etc/init/auditd.conf ']'
    which initctl
    grep -q upstart
    initctl version
    case "${ACTION}" in
    exec start auditd auditd start/running, process 12118

~# ps -ef | grep 12118
root 12219 5537 0 09:53 pts/0 00:00:00 grep --color=auto 12118

Is there a particular configuration in order to enable auditd service?
Suggestions?

Thanks in advance
Remo

**Comment by cppforlife** [comment] 2016-06-16 19:45
We have filed an issue with Canonical:

> We have identified a problem with recent stemcell versions that we tracked down to a change in lsb-base package. It appears that updating from lsb_4.1+Debian11ubuntu6 to lsb_4.1+Debian11ubuntu6.1 introduces a file called /lib/lsb/init-functions.d/01-upstart-lsb. After that change when we boot the OS, upstart (start auditd command) fails to start auditd with the log line "start: Job is already running: auditd". We have checked that auditd process is not running (ps auxww|grep auditd). Before this file was introduced auditd service would properly start and process would run.

i've entered a story https://www.pivotaltracker.com/story/show/121694777 to apply a fix without relying on fixed package. we'll release 3232.x shortly.

**Comment by cppforlife** [comment] 2016-06-17 17:25
Canonical helped us to identify the problem. We believe that https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/stemcell_builder/stages/bosh_audit/apply.sh#L23 is unnecessary for auditd startup. We are planning to remove this configuration.

**Comment by cppforlife** [comment] 2016-06-20 20:45
Fixed in 3232.11.

**Closed** 2016-06-20 20:55 UTC
Labels: filed-as-story, planned-enhancement

**Comment by mattcui** [comment] 2016-06-23 14:36
@rfreddi We built 3232.11 stemcell for Softlayer, please help verify if the problem is fixed. Thanks.

https://control.softlayer.com/devices/images/1172257

**Comment by rfreddi** [comment] 2016-07-08 13:38
@mattcui 
Hi Matt, I tested the fix in the image created and it works fine.
Anyway the auditd behavior is changed, so I'm changing my code.
So when the stemcell will be updated I need to deploy my new release version.

Thank you very much Matt and all.
