### ISSUE TITLE
`max_in_flight` not respected when adding an AZ

### ISSUE THREAD

**Issue by ekcasey** [cloudfoundry/bosh#1661] opened 2017-04-27 16:27 UTC
Given I have 3 locators and 4 servers spread across 2 AZs, when I update my deployment and **add an AZ** with `max_in_flight: 1`, bosh preforms the deployment as follows

```
Task 120

15:38:41 | Preparing deployment: Preparing deployment (00:00:00)
15:38:42 | Preparing package compilation: Finding packages to compile (00:00:00)
15:38:42 | Creating missing vms: locator/e1eba96e-dd5f-4d3b-9b97-9c11c674d48f (3)
15:38:42 | Creating missing vms: server/59c133a4-6085-4b32-b908-716b4df064bd (4) (00:01:27)
15:40:15 | Creating missing vms: locator/e1eba96e-dd5f-4d3b-9b97-9c11c674d48f (3) (00:01:33)
15:40:15 | Deleting unneeded instances locator: locator/14a80fa4-fd2e-4c7c-bc35-ce24a28e4907 (2) (00:00:48)
15:41:03 | Updating instance locator: locator/f423165b-be9f-4c54-8cda-f5c4fef02eba (0) (canary) (00:01:36)
15:42:39 | Updating instance locator: locator/f07f47a1-d39a-40a4-ba9c-ce29095899ed (1) (00:01:36)
15:44:15 | Updating instance locator: locator/e1eba96e-dd5f-4d3b-9b97-9c11c674d48f (3) (00:01:51)
15:46:06 | Deleting unneeded instances server: server/6278ccc7-3870-4772-acdb-588cd4a1371d (3) (00:01:19)
15:47:25 | Updating instance server: server/fa8b2dc6-59d1-43c1-a958-cd75c76da384 (0) (canary) (00:01:11)
15:48:36 | Updating instance server: server/ad4b0b61-74ff-488f-b60f-ead3667b6d22 (2) (canary) (00:01:05)
15:49:41 | Updating instance server: server/7754f4a0-47fe-4820-b8e6-eb78395e8fab (1) (00:01:06)
15:50:47 | Updating instance server: server/59c133a4-6085-4b32-b908-716b4df064bd (4) (00:01:19)

Started  Thu Apr 27 15:38:41 UTC 2017
Finished Thu Apr 27 15:52:06 UTC 2017
Duration 00:13:25

Task 120 done

Succeeded
```

This is a problem for us because we cannot have 2 servers down simultaneously without losing data. In the above case, this is indeed what happens. Here are the relevant steps in order:

bosh action | number of servers
------------   |  -------------------
original state | 4 servers
bosh creates a vm in the new az | 4 servers
bosh deletes a server | 3 servers
bosh starts updating an existing server | **2 servers**
bosh finishes updating the existing server | 3 servers
bosh updates the server in the new az | 4 servers

So, essentially, we have 2 instance updates "in flight" (the AZ move and a regular instance update). It seems like this happens because bosh updates one AZ a time and applies `max_in_flight` within the context of each AZ. 

**REQUEST**: When adding an AZ to a deployment, bosh should update the new AZ first.

**Comment by pulkitpivotal** [comment] 2017-07-05 21:21
@cppforlife Could we close this out soon. How can we help?

**Comment by jfmyers9** [comment] 2018-09-13 19:12
I tried to reproduce this and was unsuccessful:
```
[jfmyers9@ronaldo vbox]$ bosh -d zookeeper deploy zookeeper.yml --recreate
Using environment '192.168.50.6' as client 'admin'

Using deployment 'zookeeper'

Release 'zookeeper/0.0.9' already exists.

  instance_groups:
  - name: zookeeper
    azs:
+   - z3

Continue? [yN]: y

Task 2769

Task 2769 | 03:33:17 | Preparing deployment: Preparing deployment (00:00:00)
Task 2769 | 03:33:18 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2769 | 03:33:18 | Updating instance zookeeper: zookeeper/3396a3e3-8988-4bb8-b0d6-670014da467d (0) (canary) (00:00:38)
Task 2769 | 03:33:56 | Updating instance zookeeper: zookeeper/89f1143c-2c4b-4304-bfc9-e965afc86eb4 (2) (canary) (00:00:39)
Task 2769 | 03:34:35 | Updating instance zookeeper: zookeeper/e375c21b-9229-4110-b48a-2672ca4959ca (4) (00:00:38)
Task 2769 | 03:35:13 | Updating instance zookeeper: zookeeper/4c42c86a-4f74-414f-995f-4aa30453f9f5 (3) (00:00:39)
Task 2769 | 03:35:52 | Updating instance zookeeper: zookeeper/7ada26c3-f812-48d4-8512-b893ea60317c (1) (00:00:37)

Task 2769 Started  Thu Sep 13 03:33:17 UTC 2018
Task 2769 Finished Thu Sep 13 03:36:29 UTC 2018
Task 2769 Duration 00:03:12
Task 2769 done

Succeeded
```

Going to close this issue out due to inactivity. Feel free to reopen if this is still a problem.

**Closed by jfmyers9** 2018-09-13 19:12 UTC
Labels: discuss
