### ISSUE TITLE
`bosh deploy` was successful, HM tried to resurrect compilation VM

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1417] opened 2016-08-26 17:24 UTC
Here is it trying to bring back the compilation VM:
<details>

```

Director task 68462
I, [2016-08-24T09:34:48.007711 #6730] [0x2adb203ef118]  INFO -- TaskHelper: Director Version: 1.3262.3.0
I, [2016-08-24T09:34:48.007745 #6730] [0x2adb203ef118]  INFO -- TaskHelper: Enqueuing task: 68462
I, [2016-08-24 09:34:48 #13347] []  INFO -- DirectorJobRunner: Looking for task with task id 68462
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000168s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000215s) SELECT * FROM "tasks" WHERE "id" = 68462
I, [2016-08-24 09:34:48 #13347] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>68462, :state=>"queued", :timestamp=>2016-08-24 09:34:48 UTC, :description=>"scan and fix", :result=>nil, :output=>"/var/vcap/store/director/tasks/68462", :checkpoint_time=>2016-08-24 09:34:48 UTC, :type=>"cck_scan_and_fix", :username=>"hm", :deployment_name=>"my-deployment", :started_at=>nil}>
I, [2016-08-24 09:34:48 #13347] []  INFO -- DirectorJobRunner: Starting task: 68462
I, [2016-08-24 09:34:48 #13347] [task:68462]  INFO -- DirectorJobRunner: Creating job
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000101s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000090s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.001301s) SELECT * FROM "deployments" WHERE ("name" = 'my-deployment') LIMIT 1
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000098s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000155s) SELECT * FROM "tasks" WHERE "id" = 68462
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000098s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000149s) SELECT * FROM "tasks" WHERE "id" = 68462
I, [2016-08-24 09:34:48 #13347] [task:68462]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>68462, :state=>"queued", :timestamp=>2016-08-24 09:34:48 UTC, :description=>"scan and fix", :result=>nil, :output=>"/var/vcap/store/director/tasks/68462", :checkpoint_time=>2016-08-24 09:34:48 UTC, :type=>"cck_scan_and_fix", :username=>"hm", :deployment_name=>"my-deployment", :started_at=>nil}>
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000105s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000073s) BEGIN
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000304s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2016-08-24 09:34:48.134288+0000', "description" = 'scan and fix', "result" = NULL, "output" = '/var/vcap/store/director/tasks/68462', "checkpoint_time" = '2016-08-24 09:34:48.134374+0000', "type" = 'cck_scan_and_fix', "username" = 'hm', "deployment_name" = 'my-deployment', "started_at" = '2016-08-24 09:34:48.134334+0000' WHERE ("id" = 68462)
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000705s) COMMIT
I, [2016-08-24 09:34:48 #13347] [task:68462]  INFO -- DirectorJobRunner: Acquiring deployment lock on my-deployment
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: Acquiring lock: lock:deployment:my-deployment
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000098s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000091s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000087s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000326s) SELECT count(*) AS "count" FROM "locks" WHERE (("name" = 'lock:deployment:my-deployment') AND ("uid" = '51162d8f-74c0-420a-80e7-6f86f32df113')) LIMIT 1
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000093s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000069s) BEGIN
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000239s) INSERT INTO "locks" ("name", "uid", "expired_at") VALUES ('lock:deployment:my-deployment', '51162d8f-74c0-420a-80e7-6f86f32df113', '2016-08-24 09:34:59.136607+0000') RETURNING *
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000677s) COMMIT
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: Acquired lock: lock:deployment:my-deployment
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:my-deployment
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.001797s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000130s) SET standard_conforming_strings = ON
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000065s) SET client_min_messages = 'WARNING'
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000054s) SET DateStyle = 'ISO'
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000132s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000177s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.000102s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000111s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000436s) SELECT * FROM "instances" WHERE (("instances"."deployment_id" = 5467) AND ("job" = 'compilation-7a7ab962-a896-415d-80fe-3e1db8b797b6') AND ("uuid" = 'f69d1666-13d5-412b-a5f0-9bef7babfd69')) LIMIT 1
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000089s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: (0.001095s) UPDATE "locks" SET "expired_at" = '2016-08-24 09:34:59.140931+0000' WHERE (("name" = 'lock:deployment:my-deployment') AND ("uid" = '51162d8f-74c0-420a-80e7-6f86f32df113'))
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000142s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000098s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000766s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:my-deployment') AND ("uid" = '51162d8f-74c0-420a-80e7-6f86f32df113'))
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:my-deployment uid: 51162d8f-74c0-420a-80e7-6f86f32df113
E, [2016-08-24 09:34:48 #13347] [task:68462] ERROR -- DirectorJobRunner: 'my-deployment/compilation-7a7ab962-a896-415d-80fe-3e1db8b797b6/f69d1666-13d5-412b-a5f0-9bef7babfd69' doesn't exist
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/api/instance_lookup.rb:29:in `by_uuid'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/api/instance_manager.rb:20:in `find_by_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/problem_scanner/scanner.rb:23:in `block in reset'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/problem_scanner/scanner.rb:22:in `each'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/problem_scanner/scanner.rb:22:in `reset'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/cloud_check/scan_and_fix.rb:33:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_runner.rb:94:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/db_job.rb:24:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/db_job.rb:72:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000100s) SELECT NULL
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000070s) BEGIN
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000232s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-08-24 09:34:48.146270+0000', "description" = 'scan and fix', "result" = '''my-deployment/compilation-7a7ab962-a896-415d-80fe-3e1db8b797b6/f69d1666-13d5-412b-a5f0-9bef7babfd69'' doesn''t exist', "output" = '/var/vcap/store/director/tasks/68462', "checkpoint_time" = '2016-08-24 09:34:48.134374+0000', "type" = 'cck_scan_and_fix', "username" = 'hm', "deployment_name" = 'my-deployment', "started_at" = '2016-08-24 09:34:48.134334+0000' WHERE ("id" = 68462)
D, [2016-08-24 09:34:48 #13347] [task:68462] DEBUG -- DirectorJobRunner: (0.000822s) COMMIT
I, [2016-08-24 09:34:48 #13347] []  INFO -- DirectorJobRunner: Task took 0.017442868 seconds to process.

Task 68462 error
```

</details>

**Comment by dpb587-pivotal** [comment] 2016-09-02 23:50
Related/duplicate of #1269.

Also, `<details>`? Clever! Never considered that before.

**Comment by voelzmo** [comment] 2016-09-05 08:21
@dpb587-pivotal :)

**Comment by cppforlife** [comment] 2016-11-11 10:55
Should be covered by `expects_vm` API field now respected by the HM in v258+.

**Closed by cppforlife** 2016-11-11 10:55 UTC
