### ISSUE TITLE
clean up or re-use instances

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#979] opened 2015-10-13 09:47 UTC
When BOSH fails to deploy all the instances it needs (e.g. fails creating one out of 10 instances), it leaves the created instances behind, still running, but unused. When you try to deploy again, BOSH starts 'deleting unneeded vms', just to create them again immediately afterwards. This is not that clever. BOSH should either clean up unneeded vms immediately after it fails deployment - as it doesn't do anything with them and it already marks them/treats them as 'unneeded'. 

Alternatively, when you are doing BOSH deploy again and BOSH knows there are some VMs it has created, maybe it can just re-use them, instead of destroying and immediately creating the same VM type and count again...

1st attemtp:
```
   Failed creating bound missing vms > runner_z2/0: Unknown CPI error 'Unknown' with message 'We currently do not have sufficient r3.large capacity in the Availability Zone you requested (eu-west-1b). Our system will be working on provisioning additional capacity. You can currently get r3.large capacity by not specifying an Availability Zone in your request or choosing eu-west-1c, eu-west-1a.' (00:01:28)
     Done creating bound missing vms > medium_z1/1 (00:03:32)
     Done creating bound missing vms > small_z1/1 (00:03:39)
     Done creating bound missing vms > small_z1/2 (00:03:41)
     Done creating bound missing vms > medium_z1/4 (00:03:42)
     Done creating bound missing vms > medium_z1/5 (00:03:42)
     Done creating bound missing vms > small_z1/3 (00:03:43)
     Done creating bound missing vms > router_z1/0 (00:03:44)
     Done creating bound missing vms > runner_z1/0 (00:03:44)
     Done creating bound missing vms > medium_z1/7 (00:03:44)
     Done creating bound missing vms > medium_z1/2 (00:03:45)
     Done creating bound missing vms > large_z1/0 (00:03:46)
     Done creating bound missing vms > medium_z1/0 (00:03:47)
     Done creating bound missing vms > medium_z1/6 (00:04:10)
     Done creating bound missing vms > medium_z1/8 (00:04:13)
     Done creating bound missing vms > medium_z1/3 (00:04:18)
     Done creating bound missing vms > medium_z2/0 (00:04:25)
     Done creating bound missing vms > small_z1/0 (00:04:25)
     Done creating bound missing vms > small_z1/4 (00:04:53)
   Failed creating bound missing vms (00:04:53)

Error 100: Unknown CPI error 'Unknown' with message 'We currently do not have sufficient r3.large capacity in the Availability Zone you requested (eu-west-1b). Our system will be working on provisioning additional capacity. You can currently get r3.large capacity by not specifying an Availability Zone in your request or choosing eu-west-1c, eu-west-1a.'
```

2nd attempt:
```
  Started deleting unneeded vms
  Started deleting unneeded vms > i-369ca790
  Started deleting unneeded vms > i-3c93a89a
  Started deleting unneeded vms > i-3393a895
  Started deleting unneeded vms > i-0492a9a2
  Started deleting unneeded vms > i-8c92a92a
  Started deleting unneeded vms > i-229ca784
  Started deleting unneeded vms > i-fd93a85b
  Started deleting unneeded vms > i-aec65e17
  Started deleting unneeded vms > i-399ca79f
     Done deleting unneeded vms > i-0492a9a2 (00:01:33)
     Done deleting unneeded vms > i-aec65e17 (00:01:39)
     Done deleting unneeded vms > i-399ca79f (00:01:45)
     Done deleting unneeded vms > i-369ca790 (00:01:57)
     Done deleting unneeded vms > i-8c92a92a (00:01:59)
     Done deleting unneeded vms > i-3393a895 (00:01:59)
     Done deleting unneeded vms > i-fd93a85b (00:02:12)
     Done deleting unneeded vms > i-3c93a89a (00:02:13)
     Done deleting unneeded vms > i-229ca784 (00:02:14)
     Done deleting unneeded vms (00:02:14)

  Started creating bound missing vms
  Started creating bound missing vms > small_z1/1
  Started creating bound missing vms > small_z1/0
  Started creating bound missing vms > medium_z1/0
  Started creating bound missing vms > medium_z1/2
  Started creating bound missing vms > medium_z1/1
  Started creating bound missing vms > medium_z1/4
  Started creating bound missing vms > medium_z1/3
  Started creating bound missing vms > medium_z2/0
  Started creating bound missing vms > router_z1/0
  Started creating bound missing vms > runner_z2/0
```

BOSH v207, stemcell 3074.

**Comment by cppforlife** [comment] 2015-10-14 15:37
Agreed. I believe we may actually get proposed behavior for free once we merge our global-net branch, because we immediately assign roles to the VMs instead of what we currently do.

**Comment by mtekel** [comment] 2015-10-14 15:48
When is that expected to happen?

**Comment by bosh-ci-push-pull** [comment] 2015-10-14 15:50
As soon as we reach following marker:
https://www.pivotaltracker.com/story/show/100170490. This is a top priority
for the BOSH team.

**Comment by mtekel** [comment] 2016-03-02 11:32
Looks like this is implemented now. Whenever I get AWS rate exceeded errors, on the 2nd run BOSH only re-creates VMs it failed previously, instead of deleting everything and starting over...

**Comment by dpb587-pivotal** [comment] 2016-03-09 01:57
Closing - marker was completed a while ago and sounds like it's confirmed fix.

**Closed by dpb587-pivotal** 2016-03-09 01:57 UTC
Labels: planned-enhancement
