### ISSUE TITLE
AWS light stemcells all contain same sha1 in stemcell.MF

### ISSUE THREAD

**Issue by alext** [cloudfoundry/bosh#2118] opened 2019-01-18 15:31 UTC
**Describe the bug**

We've hit an issue because it seems that all the AWS light stemcells (for both trusty and xenial) have the same SHA1 in their `stemcell.MF` file. This value is what ends up in the bosh database:

```
bosh=> select name, sha1, version, cid, operating_system from stemcells;
                  name                   |                   sha1                   | version |             cid             | operating_system
-----------------------------------------+------------------------------------------+---------+-----------------------------+------------------
 bosh-aws-xen-hvm-ubuntu-xenial-go_agent | da39a3ee5e6b4b0d3255bfef95601890afd80709 | 170.19  | ami-058cdaa299e8eb4d7 light | ubuntu-xenial
 bosh-aws-xen-hvm-ubuntu-xenial-go_agent | da39a3ee5e6b4b0d3255bfef95601890afd80709 | 170.21  | ami-07f5c7221eeb6e650 light | ubuntu-xenial
 bosh-aws-xen-hvm-ubuntu-trusty-go_agent | da39a3ee5e6b4b0d3255bfef95601890afd80709 | 3586.67 | ami-018d9bb0f5701d830 light | ubuntu-trusty
(3 rows)
```

This has caused an issue for us because these SHA1s are [used to generate the keys](https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/models/compiled_package.rb#L6-L10) used in the global compiled package cache, and if they're identical we can end up using a package compiled for a trusty stemcell with a xenial stemcell (eg https://github.com/cloudfoundry/cf-deployment/issues/663).

**To Reproduce**

Example of the problem using capi-release:

1. Deploy a bosh director to AWS configured with a global compiled package cache
2. Deploy a minimal manifest using capi-release and a trusty stemcell.
3. Deploy the same version of capi-release using a xenial stemcell and the compilation step will fail.

(I've been testing with this dummy manifest: https://gist.github.com/alext/e9c2ed8a9e4e5f271729e1017ae69cc8, which doesn't work but gets far enough to demonstrate the compilation issue)

Inspect the stemcells:

```
$ wget -nv https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3586.67 -O trusty.tgz
2019-01-18 14:51:43 URL:https://s3.amazonaws.com/bosh-aws-light-stemcells/light-bosh-stemcell-3586.67-aws-xen-hvm-ubuntu-trusty-go_agent.tgz [19403/19403] -> "trusty.tgz" [1]
$ tar -xOf trusty.tgz stemcell.MF | grep sha1
sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
$ wget -nv https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=170.21 -O xenial.tgz
2019-01-18 14:52:18 URL:https://s3.amazonaws.com/bosh-aws-light-stemcells/light-bosh-stemcell-170.21-aws-xen-hvm-ubuntu-xenial-go_agent.tgz [19915/19915] -> "xenial.tgz" [1]
$ tar -xOf xenial.tgz stemcell.MF | grep sha1
sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
```

**Expected behavior**

I'd at least expect stemcells from different series to have different sha1 entries in their manifest. 

**Logs**
Logs can be provided if they're relevant.

**Versions (please complete the following information):**
 - Infrastructure: AWS
 - BOSH version: 268.4.0
 - BOSH CLI version: 5.2.1-24101936-2018-08-27T21:55:34
 - Stemcell version: various versions of the AWS light stemcell.

**Deployment info:**
We're using a manifest based on bosh-deployment (full source here: https://github.com/alphagov/paas-bootstrap/tree/master/manifests/bosh-manifest). I can share a redacted manifest if necessary, but I anticipate that given the nature of this issue, that won't be relevant.

**Comment by jaresty** [comment] 2019-01-28 19:48
Hi @alext,

We looked into this bug report and discovered that in fact it is [an expected behavior](https://www.pivotaltracker.com/story/show/134451441) for light stemcells to share a shasum -- in fact, that shasum is the shasum of the empty string `""`.  We have chatted with our PM about it and don't plan to change this behavior for now.  Please give us feedback if you have an argument why this is important to change.

Closing the issue for now-thanks,

@jaresty | @luan | @pivotal-mp

**Comment by alext** [comment] 2019-01-30 14:36
I believe this is a significant issue, but perhaps fix doesn't lie with the SHA in the stemcell manifest and instead the bosh director needs to be changes to use different details from the stemcell to generate the key into the compiled package cache.

As things stand, if you have the compiled package cache configured in your bosh director, upgrading from one stemcell series to another (eg moving from trusty to xenial) is very likely to result in issues because compiled packages built against trusty will then be used on a xenial machine, which won't necessarily have the same versions of libraries available (as in the capi-release example mentioned above).

**Comment by dpb587-pivotal** [comment] 2019-01-30 22:46
Hi @alext - thanks for raising this; I think it is a valid issue and worth discussing a bit more. The combination of light stemcells and their empty `image` checksums being used as a key in the compiled package cache is unfortunate. We've relied on `sha1` as part of that cache key since before light stemcells were even a feature. Nowadays, I agree, we ought to consider different keys.

That being said, the compiled package cache feature is something we're not very interested in maintaining for much longer. The feature is a bit lacking - both in functionality and modern usage. One of its significant limitations is that it offers no integrity verification of the blobs it uses. The data is based purely on a [now-proven impartial] key and there's no checksum verification that can happen between environments. In theory, if you can lock down those assets and maintain your own audit and integrity of those files, it is workable. But since BOSH can't prove those assets in the same way it is able to track and prove all other assets, we haven't really been recommending this feature. Given all that, fixing this particular issue is a very low priority for us.

I do know that it can be a convenient feature though. If you're comfortable discussing any of it here, are you open to the idea of disabling the compiled package cache in your environments? While we're at it, what impact would it have if we were to remove this feature at some point in the future? If we're considering other ways BOSH might be able to support this functionality, is your main use case to avoid the repeat compilation times across environments? Or is it for requirements that your environments use the exact same asset? Or to support environments which disable compilation?

Thanks for taking the time to track down this behavior to code and a repro case - not a trivial thing to diagnose!

**Comment by alext** [comment] 2019-02-04 11:03
Hi, thanks for the response.

Our use-case for the compiled package cache is purely a performance thing for our development environments. We have a number of slimmed-down development CF deployments, each with their own bosh director. We use the compiled package cache to avoid having to recompile packages for each environment, and each time we tear down and rebuild an environment.

So, in short, our use-case is to avoid the repeat compilation times. We don't have any requirements around using the exact same asset etc.

In the meantime we're going to investigate how much benefit this feature is actually giving us.

**Comment by belinda-liu** [comment] 2019-02-11 15:17
Hey @alext,

Was there anything else you wanted to discuss? It sounds like you were going to do some investigating on your end, not sure how much else we can help. 
If there's nothing else, we'd like to close this issue.

Thanks,
@belinda-liu && @xtreme-behrouz-soroushian

**Comment by alext** [comment] 2019-02-11 15:31
Hi @belinda-liu,

It seems that the output of this discussion is that the compiled package cache feature isn't safe to use when using light stemcells, so we're going to have to disable it. This will have a performance penalty for us in our development environments, but I think we can probably live with that.

I feel that this is something that should at least be called out in the docs though so that other people don't get bitten by the same issue.

**Comment by dpb587-pivotal** [comment] 2019-03-12 17:37
Closing – it doesn't look like we currently document this in a public way (aside from what is exposed as job properties). I'm going to be optimistic that this doesn't come up frequently rather than spend much extra time adding negative feature docs. Feel free to PR and reference this if you'd like to see something specific.

**Closed by dpb587-pivotal** 2019-03-12 17:37 UTC
Labels: triaged, unscheduled
