### ISSUE TITLE
bosh director deploy on OpenStack failed with an error ：Waiting for instance 'bosh/0' to be running... Failed

### ISSUE THREAD

**Issue by mllives** [cloudfoundry/bosh#2109] opened 2019-01-02 07:54 UTC
when i performed a deployment command on controller node, it will failed at creating bosh agent in vm bosh/0. I found it was for the reason that bosh/0 cannot running,its booting process suspend at "boot from a hard disk,grubbed...". I change the value of virt_type in compute node from kvm to qemu, i can setup a bosh agent in bosh/0. But at last it still failed at "Waiting for instance 'bosh/0' to be running... Failed" after a long time compilation. what's wrong with it? i am very confused about it ? I am really appreciated it if you can help me out.

**Comment by dpb587-pivotal** [comment] 2019-01-04 16:53
This typically occurs due to misconfiguration of one of the jobs running on your instance. With `create-env` workflows, you may want to try [installing a jumpbox user](https://bosh.io/docs/jumpbox/) to help debug. Then you can SSH and check `monit summary` to see which jobs are failing, and then take a look at `/var/vcap/sys/log/**/*` files for underlying errors.

If you're not already using it, I would recommend deploying BOSH with [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) because it has quite a bit of defaults which reduce the chances of configuration errors while you're bringing up a new environment.

**Comment by mllives** [comment] 2019-02-21 16:36
@dpb587-pivotal 

Thanks for your advice! 
But I still cannot solve this problem. I cannot  figure out where it is wrong.
I checked monit information from /var/vcap/monit/monit.log and other information from /var/vcap/sys/log/**/* files. I found nothing. 
Information in /var/vcap/monit/monit.log  as blow, it goes through the  

“ info     : 'health_monitor' process is running with pid  XXX
  error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP
   info     : 'health_monitor' exec: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
   error    : 'health_monitor' process is not running
   info     : 'health_monitor' trying to restart
   info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl  ”

cycle endlessly.

1 [UTC Feb 21 08:50:35] info     : monit: generated unique Monit id 50acf259a8fe945311dd3626be2c4744 and stored to '/root/.monit.id'
      2 [UTC Feb 21 08:50:35] info     : Starting monit daemon with http interface at [127.0.0.1:2822]
      3 [UTC Feb 21 08:50:35] info     : Starting monit HTTP server at [127.0.0.1:2822]
      4 [UTC Feb 21 08:50:35] info     : monit HTTP server started
      5 [UTC Feb 21 08:50:35] info     : 'system_localhost' Monit started
      6 [UTC Feb 21 08:50:35] error    : Cannot open a connection to the mailserver 'localhost:2825' -- Transport endpoint is not connected
      7 [UTC Feb 21 08:50:35] error    : No mail servers are available
      8 [UTC Feb 21 08:50:35] error    : Cannot open a connection to the mailserver 'localhost:2825' -- Transport endpoint is not connected
      9 [UTC Feb 21 08:50:35] error    : No mail servers are available
     10 [UTC Feb 21 08:50:35] error    : Alert handler failed, retry scheduled for next cycle
     11 [UTC Feb 21 08:55:46] info     : Starting monit daemon with http interface at [127.0.0.1:2822]
     12 [UTC Feb 21 08:55:46] info     : Starting monit HTTP server at [127.0.0.1:2822]
     13 [UTC Feb 21 08:55:46] info     : monit HTTP server started
     14 [UTC Feb 21 08:55:46] info     : 'system_localhost' Monit started
     15 [UTC Feb 21 11:48:53] info     : Starting monit daemon with http interface at [127.0.0.1:2822]
     16 [UTC Feb 21 11:48:53] info     : Starting monit HTTP server at [127.0.0.1:2822]
     17 [UTC Feb 21 11:48:53] info     : monit HTTP server started
     18 [UTC Feb 21 11:48:53] info     : 'system_localhost' Monit started
     19 [UTC Feb 21 11:49:11] info     : Starting monit daemon with http interface at [127.0.0.1:2822]
     20 [UTC Feb 21 11:49:11] info     : Starting monit HTTP server at [127.0.0.1:2822]
     21 [UTC Feb 21 11:49:11] info     : monit HTTP server started
     22 [UTC Feb 21 11:49:11] info     : 'system_localhost' Monit started
     23 [UTC Feb 21 11:49:11] error    : 'nats' process is not running
     24 [UTC Feb 21 11:49:12] info     : start service 'registry' on user request
     25 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     26 [UTC Feb 21 11:49:12] info     : start service 'health_monitor' on user request
     27 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     28 [UTC Feb 21 11:49:12] info     : start service 'director_nginx' on user request
     29 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     30 [UTC Feb 21 11:49:12] info     : start service 'director_sync_dns' on user request
     31 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     32 [UTC Feb 21 11:49:12] info     : start service 'director_scheduler' on user request
     33 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     34 [UTC Feb 21 11:49:12] info     : start service 'worker_4' on user request
     35 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     36 [UTC Feb 21 11:49:12] info     : 'nats' trying to restart
     37 [UTC Feb 21 11:49:12] info     : 'nats' start: /var/vcap/jobs/bpm/bin/bpm
     38 [UTC Feb 21 11:49:12] info     : start service 'worker_3' on user request
     39 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     40 [UTC Feb 21 11:49:12] info     : start service 'worker_2' on user request
     41 [UTC Feb 21 11:49:12] info     : monit daemon at 19414 awakened
     42 [UTC Feb 21 11:49:13] info     : start service 'worker_1' on user request
     43 [UTC Feb 21 11:49:13] info     : monit daemon at 19414 awakened
     44 [UTC Feb 21 11:49:13] info     : start service 'director' on user request
     45 [UTC Feb 21 11:49:13] info     : monit daemon at 19414 awakened
     46 [UTC Feb 21 11:49:13] info     : start service 'blobstore_nginx' on user request
     47 [UTC Feb 21 11:49:13] info     : monit daemon at 19414 awakened
     48 [UTC Feb 21 11:49:13] info     : start service 'postgres' on user request
     49 [UTC Feb 21 11:49:13] info     : monit daemon at 19414 awakened 
50 [UTC Feb 21 11:49:13] info     : start service 'nats' on user request
     51 [UTC Feb 21 11:49:13] info     : monit daemon at 19414 awakened
     52 [UTC Feb 21 11:49:21] info     : 'postgres' start: /var/vcap/jobs/bpm/bin/bpm
     53 [UTC Feb 21 11:49:28] info     : 'postgres' start action done
     54 [UTC Feb 21 11:49:30] info     : 'blobstore_nginx' start: /var/vcap/jobs/bpm/bin/bpm
     55 [UTC Feb 21 11:49:43] info     : 'blobstore_nginx' start action done
     56 [UTC Feb 21 11:49:44] info     : 'director' start: /var/vcap/jobs/bpm/bin/bpm
     57 [UTC Feb 21 11:49:55] info     : 'worker_1' start: /var/vcap/jobs/director/bin/worker_ctl
     58 [UTC Feb 21 11:49:58] info     : 'worker_2' start: /var/vcap/jobs/director/bin/worker_ctl
     59 [UTC Feb 21 11:50:01] info     : 'worker_3' start: /var/vcap/jobs/director/bin/worker_ctl
     60 [UTC Feb 21 11:50:05] info     : 'worker_4' start: /var/vcap/jobs/director/bin/worker_ctl
     61 [UTC Feb 21 11:50:10] info     : 'director' start action done
     62 [UTC Feb 21 11:50:16] info     : 'worker_1' start action done
     63 [UTC Feb 21 11:50:24] info     : 'worker_2' start action done
     64 [UTC Feb 21 11:50:32] info     : 'worker_3' start action done
     65 [UTC Feb 21 11:50:40] info     : 'worker_4' start action done
     66 [UTC Feb 21 11:50:45] info     : 'director_scheduler' start: /var/vcap/jobs/bpm/bin/bpm
     67 [UTC Feb 21 11:51:11] info     : 'director_scheduler' start action done
     68 [UTC Feb 21 11:51:15] info     : 'director_sync_dns' start: /var/vcap/jobs/bpm/bin/bpm
     69 [UTC Feb 21 11:51:42] info     : 'director_sync_dns' start action done
     70 [UTC Feb 21 11:51:47] info     : 'director_nginx' start: /var/vcap/jobs/bpm/bin/bpm
     71 [UTC Feb 21 11:52:17] error    : 'director_nginx' failed to start
     72 [UTC Feb 21 11:52:22] info     : 'director_nginx' start action done
     73 [UTC Feb 21 11:52:27] info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
     74 [UTC Feb 21 11:52:36] info     : 'health_monitor' start action done
     75 [UTC Feb 21 11:52:43] info     : 'registry' start: /var/vcap/jobs/bpm/bin/bpm
     76 [UTC Feb 21 11:53:14] error    : 'registry' failed to start
     77 [UTC Feb 21 11:53:21] info     : 'registry' start action done
     78 [UTC Feb 21 11:53:24] info     : Awakened by User defined signal 1
     79 [UTC Feb 21 11:53:27] info     : 'nats' start action done
     80 [UTC Feb 21 11:53:29] info     : 'nats' process is running with pid 19445
     81 [UTC Feb 21 11:53:33] error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP
     82 [UTC Feb 21 11:53:41] info     : 'health_monitor' exec: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
     83 ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@[UTC Feb 21 11:59:05] info     : St     83 arting monit daemon with http interface at [127.0.0.1:2822]
     84 [UTC Feb 21 11:59:05] info     : Starting monit HTTP server at [127.0.0.1:2822]
     85 [UTC Feb 21 11:59:05] info     : monit HTTP server started
     86 [UTC Feb 21 11:59:05] info     : 'system_localhost' Monit started
     87 [UTC Feb 21 11:59:05] error    : Cannot open a connection to the mailserver 'localhost:2825' -- Transport endpoint is not connected
     88 [UTC Feb 21 11:59:05] error    : No mail servers are available
     89 [UTC Feb 21 11:59:05] error    : Cannot open a connection to the mailserver 'localhost:2825' -- Transport endpoint is not connected
     90 [UTC Feb 21 11:59:05] error    : No mail servers are available
     91 [UTC Feb 21 11:59:05] error    : Alert handler failed, retry scheduled for next cycle
     92 [UTC Feb 21 11:59:05] error    : 'nats' process is not running
     93 [UTC Feb 21 11:59:05] error    : Cannot open a connection to the mailserver 'localhost:2825' -- Transport endpoint is not connected
     94 [UTC Feb 21 11:59:05] error    : No mail servers are available
     95 [UTC Feb 21 11:59:05] info     : 'nats' trying to restart
     96 [UTC Feb 21 11:59:05] info     : 'nats' start: /var/vcap/jobs/bpm/bin/bpm
     97 [UTC Feb 21 11:59:36] error    : 'nats' failed to start
98 [UTC Feb 21 11:59:36] error    : 'postgres' process is not running
     99 [UTC Feb 21 11:59:37] info     : 'postgres' trying to restart
    100 [UTC Feb 21 11:59:37] info     : 'postgres' start: /var/vcap/jobs/bpm/bin/bpm
    101 [UTC Feb 21 12:04:37] error    : 'postgres' failed to start
    102 [UTC Feb 21 12:04:37] error    : 'blobstore_nginx' process is not running
    103 [UTC Feb 21 12:04:38] info     : 'blobstore_nginx' trying to restart
    104 [UTC Feb 21 12:04:38] info     : 'blobstore_nginx' start: /var/vcap/jobs/bpm/bin/bpm
    105 [UTC Feb 21 12:05:09] error    : 'blobstore_nginx' failed to start
    106 [UTC Feb 21 12:05:09] error    : 'director' process is not running
    107 [UTC Feb 21 12:05:10] info     : 'director' trying to restart
    108 [UTC Feb 21 12:05:10] info     : 'director' start: /var/vcap/jobs/bpm/bin/bpm
    109 [UTC Feb 21 12:05:40] error    : 'director' failed to start
    110 [UTC Feb 21 12:05:40] info     : 'worker_1' start: /var/vcap/jobs/director/bin/worker_ctl
    111 [UTC Feb 21 12:05:42] info     : 'worker_2' start: /var/vcap/jobs/director/bin/worker_ctl
    112 [UTC Feb 21 12:05:44] info     : 'worker_3' start: /var/vcap/jobs/director/bin/worker_ctl
    113 [UTC Feb 21 12:05:49] info     : 'worker_4' start: /var/vcap/jobs/director/bin/worker_ctl
    114 [UTC Feb 21 12:05:55] error    : 'director_scheduler' process is not running
    115 [UTC Feb 21 12:06:04] info     : 'director_scheduler' trying to restart
    116 [UTC Feb 21 12:06:04] info     : 'director_scheduler' start: /var/vcap/jobs/bpm/bin/bpm
    117 [UTC Feb 21 12:06:34] error    : 'director_scheduler' failed to start
    118 [UTC Feb 21 12:06:40] error    : 'director_sync_dns' process is not running
    119 [UTC Feb 21 12:06:45] info     : 'director_sync_dns' trying to restart
    120 [UTC Feb 21 12:06:45] info     : 'director_sync_dns' start: /var/vcap/jobs/bpm/bin/bpm
    121 [UTC Feb 21 12:07:15] error    : 'director_sync_dns' failed to start
    122 [UTC Feb 21 12:07:21] error    : 'director_nginx' process is not running
    123 [UTC Feb 21 12:07:25] info     : 'director_nginx' trying to restart
    124 [UTC Feb 21 12:07:25] info     : 'director_nginx' start: /var/vcap/jobs/bpm/bin/bpm
    125 [UTC Feb 21 12:07:55] error    : 'director_nginx' failed to start
    126 [UTC Feb 21 12:08:02] error    : 'health_monitor' process is not running
    127 [UTC Feb 21 12:08:07] info     : 'health_monitor' trying to restart
    128 [UTC Feb 21 12:08:07] info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    129 [UTC Feb 21 12:08:11] error    : 'registry' process is not running
    130 [UTC Feb 21 12:08:20] info     : 'registry' trying to restart
    131 [UTC Feb 21 12:08:20] info     : 'registry' start: /var/vcap/jobs/bpm/bin/bpm
    132 [UTC Feb 21 12:08:51] error    : 'registry' failed to start
    133 [UTC Feb 21 12:09:34] error    : 'nats' process is not running
    134 [UTC Feb 21 12:09:34] info     : 'nats' trying to restart
    135 [UTC Feb 21 12:09:34] info     : 'nats' start: /var/vcap/jobs/bpm/bin/bpm
    136 [UTC Feb 21 12:10:05] error    : 'nats' failed to start
    137 [UTC Feb 21 12:10:05] error    : 'postgres' process is not running
    138 [UTC Feb 21 12:10:05] info     : 'postgres' trying to restart
    139 [UTC Feb 21 12:10:05] info     : 'postgres' start: /var/vcap/jobs/bpm/bin/bpm
    140 [UTC Feb 21 12:10:34] info     : 'postgres' started
    141 [UTC Feb 21 12:10:47] error    : 'blobstore_nginx' process is not running
    142 [UTC Feb 21 12:10:47] info     : 'blobstore_nginx' trying to restart
    143 [UTC Feb 21 12:10:47] info     : 'blobstore_nginx' start: /var/vcap/jobs/bpm/bin/bpm
    144 [UTC Feb 21 12:11:17] error    : 'blobstore_nginx' failed to start
    145 [UTC Feb 21 12:11:17] error    : 'director' process is not running
146 [UTC Feb 21 12:11:17] info     : 'director' trying to restart
147 [UTC Feb 21 12:11:17] info     : 'worker_1' stop: /var/vcap/jobs/director/bin/worker_ctl
    148 [UTC Feb 21 12:11:25] info     : 'worker_2' stop: /var/vcap/jobs/director/bin/worker_ctl
    149 [UTC Feb 21 12:11:32] info     : 'worker_3' stop: /var/vcap/jobs/director/bin/worker_ctl
    150 [UTC Feb 21 12:11:37] info     : 'worker_4' stop: /var/vcap/jobs/director/bin/worker_ctl
    151 [UTC Feb 21 12:11:44] info     : 'director' start: /var/vcap/jobs/bpm/bin/bpm
    152 [UTC Feb 21 12:12:04] info     : 'director' started
    153 [UTC Feb 21 12:12:07] info     : 'worker_1' start: /var/vcap/jobs/director/bin/worker_ctl
    154 [UTC Feb 21 12:12:10] info     : 'worker_2' start: /var/vcap/jobs/director/bin/worker_ctl
    155 [UTC Feb 21 12:12:13] info     : 'worker_3' start: /var/vcap/jobs/director/bin/worker_ctl
    156 [UTC Feb 21 12:12:18] info     : 'worker_4' start: /var/vcap/jobs/director/bin/worker_ctl
    157 [UTC Feb 21 12:12:22] error    : 'director_scheduler' process is not running
    158 [UTC Feb 21 12:12:22] info     : 'director_scheduler' trying to restart
    159 [UTC Feb 21 12:12:22] info     : 'director_scheduler' start: /var/vcap/jobs/bpm/bin/bpm
    160 [UTC Feb 21 12:12:52] info     : 'director_scheduler' started
    161 [UTC Feb 21 12:13:02] error    : 'director_sync_dns' process is not running
    162 [UTC Feb 21 12:13:02] info     : 'director_sync_dns' trying to restart
    163 [UTC Feb 21 12:13:02] info     : 'director_sync_dns' start: /var/vcap/jobs/bpm/bin/bpm
    164 [UTC Feb 21 12:13:34] error    : 'director_sync_dns' failed to start
    165 [UTC Feb 21 12:13:34] error    : 'director_nginx' process is not running
    166 [UTC Feb 21 12:13:34] info     : 'director_nginx' trying to restart
    167 [UTC Feb 21 12:13:34] info     : 'director_nginx' start: /var/vcap/jobs/bpm/bin/bpm
    168 [UTC Feb 21 12:14:08] error    : 'director_nginx' failed to start
    169 [UTC Feb 21 12:14:08] info     : 'health_monitor' process is running with pid 1522
    170 [UTC Feb 21 12:14:18] error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP
    171 [UTC Feb 21 12:14:29] info     : 'health_monitor' exec: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    172 [UTC Feb 21 12:14:29] error    : 'registry' process is not running
    173 [UTC Feb 21 12:14:29] info     : 'registry' trying to restart
    174 [UTC Feb 21 12:14:29] info     : 'registry' start: /var/vcap/jobs/bpm/bin/bpm
    175 [UTC Feb 21 12:15:01] error    : 'registry' failed to start
    176 [UTC Feb 21 12:15:13] info     : 'nats' process is running with pid 1595
    177 [UTC Feb 21 12:15:21] info     : 'postgres' process is running with pid 1653
    178 [UTC Feb 21 12:15:26] info     : 'blobstore_nginx' process is running with pid 1725
    179 [UTC Feb 21 12:15:38] info     : 'director' process is running with pid 1875
    180 [UTC Feb 21 12:15:47] info     : 'director_scheduler' process is running with pid 1972
    181 [UTC Feb 21 12:15:51] info     : 'director_sync_dns' process is running with pid 2017
    182 [UTC Feb 21 12:16:02] info     : 'director_nginx' process is running with pid 2061
    183 [UTC Feb 21 12:16:10] error    : 'health_monitor' process is not running
    184 [UTC Feb 21 12:16:22] info     : 'health_monitor' trying to restart
    185 [UTC Feb 21 12:16:22] info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    186 [UTC Feb 21 12:16:29] info     : 'registry' process is running with pid 2122
    187 [UTC Feb 21 12:16:49] info     : 'health_monitor' process is running with pid 2187
    188 [UTC Feb 21 12:17:03] error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP
    189 [UTC Feb 21 12:17:03] info     : 'health_monitor' exec: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    190 [UTC Feb 21 12:17:15] error    : 'health_monitor' process is not running
    191 [UTC Feb 21 12:17:24] info     : 'health_monitor' trying to restart
    192 [UTC Feb 21 12:17:24] info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    193 [UTC Feb 21 12:17:43] info     : 'health_monitor' process is running with pid 2215
    194 [UTC Feb 21 12:17:47] error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP
    195 [UTC Feb 21 12:17:47] info     : 'health_monitor' exec: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
196 [UTC Feb 21 12:17:59] error    : 'health_monitor' process is not running
    197 [UTC Feb 21 12:18:06] info     : 'health_monitor' trying to restart
    198 [UTC Feb 21 12:18:06] info     : 'health_monitor' start: /var/vcap/jobs/health_monitor/bin/health_monitor_ctl
    199 [UTC Feb 21 12:18:25] info     : 'health_monitor' process is running with pid 2235
    200 [UTC Feb 21 12:18:29] error    : 'health_monitor' failed, cannot open a connection to INET[localhost:25923/healthz] via TCP

**Comment by dpb587-pivotal** [comment] 2019-02-21 16:45
Make sure you're looking at logs in `/var/vcap/sys/log/health_monitor/*` for more detailed hints. Occasionally health monitor will not emit error messages for things like bad/untrusted certificates on the director's side or if it's communicating with an entirely incorrect director host/IP or using bad credentials.

I'd recommend checking all of those configuration properties (might be easiest to look at the configuration values in `/var/vcap/jobs/health_monitor/config/*` if there's any doubt around what values your manifest might be using.

And, again, a reminder about bosh-deployment - these issues are much less likely to occur if using that development deployment repository to get started.

**Comment by mllives** [comment] 2019-02-21 17:30
@dpb587-pivotal 
Thanks a lot!

I checked logs in /var/vcap/sys/log/health_monitor/*. There are two logs in /var/vcap/sys/log/health_monitor/. But they are both empty.

I checked values in /var/vcap/jobs/health_monitor/config/*. There seems to be no problem.

I used bosh-deployment to deploy Director VM and Bosh on OpenStack.

**Comment by tosone** [comment] 2019-09-26 07:11
I met this issue again, any ideas?

**Comment by tosone** [comment] 2019-09-26 15:22
I want to know which Openstack is current bosh which compatible with? Openstack queens and stein are all failed.

**Comment by tosone** [comment] 2019-09-26 15:27
Though I got an error that "Waiting for instance 'bosh/0' to be running...", I can run `bbl ssh --jumpbox`, then get a right response `wget --no-check-certificate https://10.0.1.6:8443` in jumpbox vm.

**Comment by mllives** [comment] 2019-09-26 15:33
not about version，maybe there is something wrong with the parameter you have set


 
---Original---

**Comment by mllives** [comment] 2019-09-26 15:37
i donnot know if it is the same problem that we met. i was confused by it for nearly 3 months. At last i found i set the wrong parameter before. tomorrow i will tell you my solution， because i forget how to solve it.


 
---Original---

**Comment by tosone** [comment] 2019-09-26 15:47
@mllives Thank you very much for your response. I cannot find your contact. You can contact me with my phone 08617010209162 or wechat: 17010209162.

**Comment by mrosecrance** [comment] 2019-10-21 22:37
It's hard to identify the issue that's being brought up without specific reproducible steps. It also seems like two separate issues, one with a custom deploy and the other with bbl. I'm going to close this as it looks like the original issue was a configuration problem that was figured out. 

There's also a tool to validate your [OpenStack setup](https://github.com/cloudfoundry-incubator/cf-openstack-validator) and a slack channel where debugging is more commonly discussed, cloudfoundry/openstack.

**Closed by mrosecrance** 2019-10-21 22:37 UTC
Labels: unscheduled
