### ISSUE TITLE
Timeout during instance update when recreating many instances

### ISSUE THREAD

**Issue by NautiluX** [cloudfoundry/bosh#2124] opened 2019-01-23 15:54 UTC
**Describe the bug**

When deploying CloudFoundry with a high number of VMs (i.e. diego-cells > 500) we
reproducibly are able to deploy a couple of the vms and then run into

```
Task 1788328 | 19:08:05 | Updating instance diego-cell: diego-cell/ba4535ec-221f-4e31-ae1b-f8430a8753d7 (793) (00:13:46)
                     L Error: Timed out sending 'update_settings' to f840b722-4daa-4bc4-a31b-4c22ac74309b after 45 seconds
```

for various different NATS messages, not only `update_settings`.

After running `bosh deploy` several times, the CloudFoundry deployment
eventually succeeds by successfully updating some instances each run.

This bug appeared only after we switched on bosh-dns.

**To Reproduce**

Steps to reproduce the behavior (example):
1. Deploy a bosh director on probably any IaaS
1. Deploy CloudFoundry with > 500 cells
1. Redeploy with --recreate

We are currently working on an easier way to reproduce it. Progress tracked in story [#163348595](https://www.pivotaltracker.com/story/show/163348595). If you have an idea how to reproduce it easily please let us know.

**Expected behavior**

Cloudfoundry gets deployed without an error.

**Versions (please complete the following information):**

- BOSH version: 268.x

**Investigation**

We instrumented the bosh director to log when messages are sent and
received [here](https://github.com/cloudfoundry/bosh/commit/52ad578fcbc0584d78b2084cfe7845aa59735b97#diff-d5148be00cadd8a5875c78af433476d3).
In addition, we enabled log output from NATS by editing the [bpm.yml](https://github.com/cloudfoundry/bosh/blob/724c38cefe2ccb993360864c15a78b56b11f82a6/jobs/nats/templates/bpm.yml#L6), adding "-DV" as argument to `gnatsd`.

A message resulting in a timeout
* is published in the NATS client library, but no answer is received
* is not received by the NATS server

In critical phases, the bosh director tries to send 15000 `sync_dns` requests
from which only a significantly smaller number receives an answer.
However, timed out `sync_dns` requests do not result in failing deployments.

**Mitigation**

We mitigated the problem by commenting out [this line](https://github.com/cloudfoundry/bosh/blob/444de6a2bed256adee98df0695151698a6023378/src/bosh-director/lib/bosh/director/dns/blobstore_dns_publisher.rb#L37).
This leads to the director not sending `sync_dns` calls when a vm gets updated.
Instead it only relies on the 10s interval for bosh-dns synchronization.

**Comment by beyhan** [comment] 2019-01-24 07:45
PR https://github.com/cloudfoundry/bosh/pull/2121 is related to this issue

**Comment by BeckerMax** [comment] 2019-01-25 10:10
Steps to reproduce this issue with bosh-lite:

1. Modify vbox cpi to use 4 cores and 26GB ram for the director vm. Add `cpus: 4` and 
`memory: 26000` [here](https://github.com/cloudfoundry/bosh-deployment/blob/master/virtualbox/cpi.yml#L20-L21).
1. Deploy vbox director with the [create-env](https://github.com/cloudfoundry/bosh-deployment/blob/master/virtualbox/create-env.sh) script.
1. Upload [bosh-dns runtime config](https://raw.githubusercontent.com/cloudfoundry/bosh-deployment/master/runtime-configs/dns.yml)
1. Deploy [dummy deployment](https://github.com/pivotal-cf-experimental/dummy-boshrelease) with `250 instances` and `max_in_flight 40`.
1. Trigger deploy with --recreate

We observe that 6 instances get a `Error: Timed out sending 'method' to instance`.

Findings with above described log instrumentation for a timed out nats request:
* Between [this line](https://github.com/cloudfoundry/bosh/blob/52ad578fcbc0584d78b2084cfe7845aa59735b97/src/bosh-director/lib/bosh/director/nats_rpc.rb#L52) and [this line](https://github.com/cloudfoundry/bosh/blob/52ad578fcbc0584d78b2084cfe7845aa59735b97/src/bosh-director/lib/bosh/director/nats_rpc.rb#L63) 17 seconds pass (this is not the reason for the timeout)
* While request is logged to be send and published the request is never received by the nats server. This can be observed by grepping for the nats request ID in the `/var/vcap/sys/log/nats/nats.log`

Note that the timeout do not occur when bosh-dns is disabled (i.e. when not uploading the runtime config).

**Comment by jfmyers9** [comment] 2019-04-08 19:20
We believe that this will be much better in the next release of BOSH. We have chosen to only send the `sync_dns` message to the instance that is being updated, rather than broadcasting it to every instance in the deployment.

I'm going to close this issue in the meantime. Please feel free to re-open if the next release does not fix your issue.

**Comment by videlov** [comment] 2019-05-21 12:47
We are still facing the issue with BOSH version `v269.0.1`.

Current setup are 1400 diego cells resulting into a NATS timeouts. Setting max DB connections to 300 and increasing the AgentClient timeout for NATS message to 90 seconds doesn't resolve the issue. We were able to validate that the NATS server didn't receive the timed out messages.

**Comment by miguelverissimo** [comment] 2019-06-06 14:06
@videlov Thank you for reopening this, and adding the extra context.

**Comment by videlov** [comment] 2019-06-06 14:37
@miguelverissimo we are still working on the analysis of the issue and will update with more details soon.

**Comment by BeckerMax** [comment] 2020-04-17 11:47
Fixed with https://github.com/cloudfoundry/bosh/pull/2254

**Closed by BeckerMax** 2020-04-17 11:47 UTC
Labels: unscheduled
