### ISSUE TITLE
Specifying "latest" version and also directory path URL for release gives weird error during deploy

### ISSUE THREAD

**Issue by amitkgupta** [cloudfoundry/bosh#1044] opened 2015-11-29 02:43 UTC
If I have the following in my manifest

```
release:
  - name: hello
    version: latest
    url: file:///path/to/release/dir
```

And I `bosh deploy`, I get an error like:

```
Cannot find file `/var/folders/3z/st02pqt10q7fx_s715rxxwqr0000gn/T/d20151128-13417-1bojzdd/d20151128-13417-1i5h4o3/release.MF'
```

I think it should either use `latest` and ignore the `url` information, or fail with an informative error message, saying that you can't specify "latest" version and also specify a URL simultaneously for a release.  I think the latter is better UX, but I'm not sure what is easier to implement in the CLI codebase.  What would be the best solution here?  Happy to try and submit a PR.

**Comment by bosh-ci-push-pull** [comment] 2015-11-30 04:44
This appears to be a duplicate of:

https://www.pivotaltracker.com/story/show/108826704

**Comment by dpb587-pivotal** [comment] 2016-05-19 23:06
Closing - the referenced story was fixed in [v234](https://github.com/cloudfoundry/bosh/releases/tag/stable-3148).

**Closed by dpb587-pivotal** 2016-05-19 23:06 UTC
