### ISSUE TITLE
`bosh snapshot` does not fail when `enable_snapshots: true` is missing from the bosh config

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/bosh#1085] opened 2016-01-06 15:28 UTC
In the documentation we see that [`enable_snapshots: true`](http://bosh.io/docs/snapshots.html) needs to be present in the BOSH configuration before snapshotting will work.

However, the bosh command line tool will give the impression that snapshotting has occurred, even if this config is not set:

```
$ bosh take snapshot
Acting as user 'admin' on deployment 'example' on 'my-bosh'
Are you sure you want to take a snapshot of all deployment 'example'? (type 'yes' to continue): yes

Director task 782

Task 782 done

Snapshot taken


$ bosh snapshots
Acting as user 'admin' on deployment 'example' on 'my-bosh'

No snapshots
```

Preferably, bosh CLI would refuse to snapshot when snapshotting is not enabled.

**Comment by cppforlife** [comment] 2016-01-07 00:54
That makes sense.

**Comment by jfmyers9** [comment] 2018-08-08 15:52
Confirmed this is still an issue on recent version of the director/cli:
```
[jfmyers9@ronaldo vbox]$ bosh -d bpm take-snapshot bpm/0
Using environment '192.168.50.6' as client 'admin'

Using deployment 'bpm'

Task 8. Done

Succeeded
[jfmyers9@ronaldo vbox]$ bosh -d bpm snapshots
Using environment '192.168.50.6' as client 'admin'

Using deployment 'bpm'

Instance  CID  Created At  Clean

0 snapshots

Succeeded
```
Created a story to track this: https://www.pivotaltracker.com/story/show/159629201

**Comment by voelzmo** [comment] 2019-06-06 10:18
closing in favor of #2161 because it has additional context of a discussion.

**Closed by voelzmo** 2019-06-06 10:18 UTC
Labels: open-for-contribution, triaged
