### ISSUE TITLE
Director issues 302 redirects to wrong port

### ISSUE THREAD

**Issue by findneville** [cloudfoundry/bosh#1641] opened 2017-03-28 19:43 UTC
Kind of the same issue as https://github.com/cloudfoundry/bosh/issues/595 

Current bosh version : 1.3262.23.0

Issuing a vms request for a deployment with format=full redirects to the wrong port (443) instead of port 25555

* Connection #0 to host dirIP left intact
* Issue another request to this URL: 'https://dirIP/tasks/47807'
* Found bundle for host dirIP: 0x1b35240
* About to connect() to dirIP port 443 (#1)
*   Trying dirIP...
* Connection refused
* Failed connect to dirIP:443; Connection refused
* Closing connection 1

Steps to reproduce

>> Gets UAA endpoint uaa_endpoint
curl -k https://dirIP:25555/info 

>> Get UAA token token
curl -skL -XPOST -u username:pwd uaa_endpoint/oauth/token --data-urlencode "grant_type=client_credentials" --data-urlencode "response_type=token"

>> Retrieve deployments deployment
curl -skL https://dirIP:25555/deployments -H "Authorization: bearer token" -v

>> Retrieve vms on a deployments
curl -skL https://dirIP:25555/deployments/deployment/vms?format=full -H "Authorization: bearer token" -v

Gives the following error!! 
* Connection #0 to host dirIP left intact
* Issue another request to this URL: 'https://dirIP/tasks/47807'
* Found bundle for host dirIP: 0x1b35240
* About to connect() to dirIP port 443 (#1)
*   Trying dirIP...
* Connection refused
* Failed connect to dirIP:443; Connection refused
* Closing connection 1

**Comment by dpb587-pivotal** [comment] 2017-03-30 00:19
Closing - duplicate of #1253

**Closed by dpb587-pivotal** 2017-03-30 00:19 UTC
