### ISSUE TITLE
Restarting the BOSH VM Results in a Broken Director 

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [cloudfoundry/bosh#2131] opened 2019-02-01 01:58 UTC
**Describe the bug**

After restarting the BOSH Director VM directly through the IAAS or by simply typing `reboot` from within the VM, the jobs on the VM will take around 10 to 15 minutes to get into a running state; except for the `credhub` job which stays in an `Execution failed` state.

Even after `monit` reports that all the jobs (except `credhub`) are in the `running` state, I will get a UAA error when trying to interact with the BOSH director through the CLI.  

A colleague and I were able to 100% reproduce this issue on AWS and Azure (we tried 7 times in total).

**To Reproduce**
1. Deploy a BOSH Director on AWS/Azure etc.. with UAA and Credhub enabled. Include the `jumpbox` ops file for easier debugging.
2. Restart the BOSH Director VM either through the IAAS or from within the VM itself with `reboot`
3. Log into the director VM and run `monit summary`. You will see that the Jobs will be in an `Initializing / Failed` state for around 10 to 15 minutes.
4. After waiting for around 15 minutes, you'll will see that `monit` reports all the jobs running, except for `credhub`.
5. Try to run `bosh env` targeting that director environment. This should theoretically succeed even if the `credhub` job is failing since credhub is not needed for this call. But `bosh env` will fail with `Requesting token via client credentials grant: UAA responded with non-successful status code '503' response 'FAILURE'`
6. From within the BOSH director VM, run `monit restart all`. This should bring the director into a working state again, or at least this worked for me multiple times.
7. **Note:** there were no running tasks when we rebooted the BOSH VM.
8. **Note:** I think `credhub` remaining in a failed state after the reboot is due to the fact that it tries to contact the `uaa` server when it starts and bails out when it cannot reach it after certain amount of time. So I think it is just a symptom of the issue, not a cause.

**Expected behavior**
I would like the BOSH director jobs to survive a VM reboot (it used to do that in previous BOSH versions). Sometimes an IAAS can take an action which reboots a director VM; this can lead to a broken state where a user cannot interact with the BOSH director API without manual intervention as described above.
Also, it is more convenient to have the jobs on the BOSH VM recover a hard VM reboot. 

**Versions:**
 - Infrastructure: We tried on AWS and Azure
 - BOSH version: `268.6.0`

**Deployment info:**
Used an unmodified bosh-deployment to create the bosh director. Exact version for bosh-deployment: [576426](https://github.com/cloudfoundry/bosh-deployment/tree/5764262202604951ac6723ddec45f26536c208c5)

**Comment by degaurab** [comment] 2019-02-04 14:48
Hi @pivotal-jamil-shamy
Can you share job logs related to the failure. As most of the authentication/authorization is done using UAA it might be causing failure upstream. Also if DB is not up before UAA start talking to it and other component will cause major failures.

Thanks

**Comment by pivotal-jamil-shamy** [comment] 2019-02-04 15:16
@degaurab I do not have any logs handy right now, but I can share them with you if you want. 
Though the issue is 100% reproducible; you should be able to easily reproduce it and check any specific logs in your environment. Probably more practical this way.

**Comment by dsboulder** [comment] 2019-03-07 21:25
I also noticed that the blobstore nginx does not come back up when rebooted because the unix socket is still present (the pre-start to clean it out doesn't run). This used to work because the socket was on a tmpfs, but when we switched to BPM a year ago we moved the socket to `/var/vcap/data` which does survive a reboot.

**Comment by dpb587-pivotal** [comment] 2019-03-13 16:56
This reminds me of the change we made around always cleaning up `backend.sock` in https://github.com/cloudfoundry/bosh/commit/075222d25c028e7e828394a45633e30bbbc7c127 and it's respective, [internal story](https://www.pivotaltracker.com/n/projects/2197715/stories/159781617).

**Comment by voelzmo** [comment] 2019-03-14 09:45
Should we move this functionality to [bpm's pre-start](https://bosh.io/docs/bpm/config/#hooks-schema) instead to ensure it is always called before executing start?

**Comment by daniellavoie** [comment] 2019-06-01 01:27
I'm also reproducing this issue on vSphere. I can help provide any type if logs if needed.

**Comment by patrickcrocker** [comment] 2019-06-09 23:49
+1

vSphere homelab suffered a power outage.  everything but bosh came back up clean.  I got the same `503` response error reporte3d here.

**Comment by svrc-pivotal** [comment] 2019-07-11 03:50
This is fixed indirectly by ensuring that the BOSH director deployment upgrades to bpm 1.0.4, which relaxes failure when pid flies are missing.   There is otherwise a race condition with monit restarts that causes UAA to be in a long duration silent failure due to a flaw in monit’s http health checking.

**Comment by daniellavoie** [comment] 2019-07-12 20:55
Awesome analysis @svrc-pivotal, guess then we can close this issue as it's not the right place, and `bosh-deployment` now references bpm 1.1.0 on `master`

**Comment by mfine30** [comment] 2019-09-18 19:26
UAA v74.1.0 is now part of bosh-deployment which should also resolve this issue. Please let us know if you continue to see problems with the updated versions after upgrading.

**Closed by mfine30** 2019-09-18 19:26 UTC
Labels: accepted, triaged
