### ISSUE TITLE
Error 450001: Action Failed get_task: Task XXXX result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

### ISSUE THREAD

**Issue by Senthilannaswamy** [cloudfoundry/bosh#1643] opened 2017-03-30 09:38 UTC
Hi All,

While "bosh deploy", I'm getting error stating

> Started updating instance api_z1 > api_z1/82ff7a83-5344-49d9-9a4a-faf068a564d6 (0) (canary). Failed: Action Failed get_task: Task 74aeb2da-0e6b-45a2-6338-d0499189ebf5 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng. (00:05:12)
> 
> Error 450001: Action Failed get_task: Task 74aeb2da-0e6b-45a2-6338-d0499189ebf5 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

Log from api_z1
api_z1/82ff7a83-5344-49d9-9a4a-faf068a564d6:/var/vcap/sys/log/cloud_controller_ng$ tail -f post-start.stderr.log

> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:59:in `run_canary'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:42:in `install'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/tasks/buildpacks.rake:7:in `block (3 levels) in <top (required)>'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:39:in `setup_environment'
> [2017-03-30 05:35:54+0000] /var/vcap/data/packages/cloud_controller_ng/ad44c9b9ce2f7a8caab73519ee20e4ac92a61d70/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (2 levels) in <top (required)>'
> [2017-03-30 05:35:54+0000] /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'

I'm trying to deploy CF on AWS following the link.
http://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html

Please note, we trying to deploy on different IP range (10.11.x.x), with a bit of ruby code to update the IP, subnet name, security group name, RDS name and ELB. I was able to complete the "bosh aws create", successfully.

Regarding cf-stub manifest, Login saml - set with the key pair generated using generate-uaa-certs.sh

In cf-deployment, 
1. api_z1 .templates - update with the following 
  - name: consul_agent
    release: cf
2. blobstore - added the properties to deploy the VM for blobstore

Please let me know where I'm making mistake.
[cf-deployment - Copy.txt](https://github.com/cloudfoundry/bosh/files/881663/cf-deployment.-.Copy.txt)
[cf-stub - Copy.txt](https://github.com/cloudfoundry/bosh/files/881664/cf-stub.-.Copy.txt)

**Comment by dpb587-pivotal** [comment] 2017-03-30 18:35
Glad you're trying out Cloud Foundry! Although bosh is emitting this error, it's being caused by cf-release and we don't have enough experience with that individual release to provide suggestions. Please feel free to follow up with an issue on the [cf-release](https://github.com/cloudfoundry/cf-release) repo, or join the [cloudfoundry#cf-users slack](https://slack.cloudfoundry.org) for more help.

Another tip... I see the tail'd log output, but you should probably include a few more lines. It looks like a backtrace and it will be easier for them to debug if it includes the original error message which is probably a few lines earlier.

Closing, but feel free to post another comment if you're having trouble finding the correct people to ask.

**Closed by dpb587-pivotal** 2017-03-30 18:35 UTC
