### ISSUE TITLE
bosh-director : Showing tasks for given deployment doesn't work if the deployment has been deleted

### ISSUE THREAD

**Issue by holgerkoser** [cloudfoundry/bosh#1211] opened 2016-04-13 11:18 UTC
Hi,

the `bosh-director` allows to filter the list of recent tasks by different critiria (limit, state and deployment_name). If I for example list the latest 3 recents tasks I get the following result: 

``` bash
$ bosh tasks recent 3
Acting as user 'admin' on 'Bosh Lite Director'

+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
| #   | State | Timestamp               | User      | Deployment  | Description           | Result           |
+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
| 930 | done  | 2016-04-12 13:19:08 UTC | admin     | bar         | delete deployment bar | /deployments/bar |
| 927 | done  | 2016-04-12 13:13:44 UTC | admin     | bar         | create deployment     | /deployments/bar |
| 925 | done  | 2016-04-12 12:57:08 UTC | admin     | foo         | create deployment     | /deployments/foo |
+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
Showing 3 recent tasks
```

I see there are two deployments `foo` and `bar`. The deployment foo has been created but not deleted and the deployment `bar` which has been created and deleted afterwards. If I list the tasks for deployment `foo` I get the following result as expected:

``` bash
$ bosh tasks --deployment foo
Acting as user 'admin' on 'Bosh Lite Director'

+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
| #   | State | Timestamp               | User      | Deployment  | Description           | Result           |
+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
| 925 | done  | 2016-04-12 12:57:08 UTC | admin     | foo         | create deployment     | /deployments/foo |
+-----+-------+-------------------------+-----------+-------------+-----------------------+------------------+
Showing 1 recent tasks
```

But if I list the tasks for deployment `bar` I get an error that the deployment doesn't exist which is true but not the correct behaviour from my point of view. I would expect to see a list with the "create deployment" and "delete deployment bar" tasks.

``` bash
$ bosh tasks --deployment bar
Acting as user 'admin' on 'Bosh Lite Director'
Error 70000: Deployment `bar' doesn't exist
```

Best regards, Holger

**Comment by allomov** [comment] 2016-04-13 12:53
Hi @holgerkoser. I share your confusion on this case. If you have access to list of all tasks (even if from removed deployments), you should be able to filter this tasks by deployment. 

As I see, this is expected behaviour of bosh-director, because of [this specs](https://github.com/cloudfoundry/bosh/blob/master/bosh-director/spec/unit/api/controllers/tasks_controller_spec.rb#L228-L231).

Think it can be fixed rather quickly.

**Comment by allomov** [comment] 2016-04-13 13:22
@holgerkoser I've created a PR #1212 to address this issue.

**Comment by holgerkoser** [comment] 2016-04-13 13:39
@allomov Thanks a lot for your assistance. Your PR looks reasonable to me.

**Comment by avade** [comment] 2016-05-09 11:08
@cppforlife has this been scheduled? Also causing our team an issue.

**Comment by dpb587-pivotal** [comment] 2016-11-11 01:54
This was fixed in director [v257](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262).

**Closed by dpb587-pivotal** 2016-11-11 01:54 UTC
