### ISSUE TITLE
Can't apply a blank runtime config

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/bosh#1645] opened 2017-04-03 13:35 UTC
1. We had a director with no runtime config
1. We applied a runtime config
1. `bosh deploy`
1. We want to rollback the runtime config application, so `bosh update-runtime-config` with a blank file
1. We `bosh deploy` and then we get an error

```
Using environment '10.0.0.5' as '?'

Task 1537

13:23:51 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: undefined method `[]' for nil:NilClass

13:23:51 | Error: undefined method `[]' for nil:NilClass

Started  Mon Apr  3 13:23:51 UTC 2017
Finished Mon Apr  3 13:23:51 UTC 2017
Duration 00:00:00

Task 1537 error

Capturing task '1537' output:
  Expected task '1537' to succeed but was state is 'error'

Exit code 1
```

In the debug logs we can see:
```
....................
D, [2017-04-03 13:23:51 #8922] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000247s) SELECT NULL
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000152s) SELECT NULL
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000076s) SELECT NULL
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.002032s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:cf-8135a7275b998ea8f846') AND ("uid" = 'd6b13bea-1cc8-4db2-b16d-dff0105df053'))
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:cf-8135a7275b998ea8f846 uid: d6b13bea-1cc8-4db2-b16d-dff0105df053
I, [2017-04-03 13:23:51 #8922] [task:1537]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"1e59320f-b6a3-4300-87da-428e1c0537a0","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'cf-8135a7275b998ea8f846' against Director '63b23a6e-0776-4e59-88f7-a61eeaf75553': #<NoMethodError: undefined method `[]' for nil:NilClass>","created_at":1491225831,"deployment":"cf-8135a7275b998ea8f846"}
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000405s) SELECT NULL
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000053s) BEGIN
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000265s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (21961, '2017-04-03 13:23:51.678249+0000', 'ops_manager', 'update', 'deployment', 'cf-8135a7275b998ea8f846', 'undefined method `[]'' for nil:NilClass', '1537', 'cf-8135a7275b998ea8f846', NULL, '{}') RETURNING *
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.001577s) COMMIT
E, [2017-04-03 13:23:51 #8922] [task:1537] ERROR -- DirectorJobRunner: undefined method `[]' for nil:NilClass
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/models/runtime_config.rb:25:in `tags'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:114:in `parse_tags'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:72:in `parse_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/deployment_plan/planner_factory.rb:43:in `create_from_manifest'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/update_deployment.rb:74:in `block (2 levels) in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/update_deployment.rb:72:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/update_deployment.rb:58:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/job_runner.rb:106:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.2.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.2.0/lib/bosh/director/jobs/db_job.rb:80:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000109s) SELECT NULL
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.000042s) BEGIN
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.001011s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2017-04-03 13:23:51.682560+0000', "description" = 'create deployment', "result" = 'undefined method `[]'' for nil:NilClass', "output" = '/var/vcap/store/director/tasks/1537', "checkpoint_time" = '2017-04-03 13:23:51.427125+0000', "type" = 'update_deployment', "username" = 'ops_manager', "deployment_name" = 'cf-8135a7275b998ea8f846', "started_at" = '2017-04-03 13:23:51.427069+0000', "context_id" = '' WHERE ("id" = 1537)
D, [2017-04-03 13:23:51 #8922] [task:1537] DEBUG -- DirectorJobRunner: (0.001723s) COMMIT
I, [2017-04-03 13:23:51 #8922] []  INFO -- DirectorJobRunner: Task took 0.261918264 seconds to process.

```

What is the correct way to un-applying a runtime config?

cc: @gcapizzi

**Comment by dpb587-pivotal** [comment] 2017-04-03 16:58
Thanks for the well-written write-up! Since #1369 already discusses this, I'm going to close it as a duplicate. Feel free to +1/subscribe to that issue for notifications on progress.

**Closed by dpb587-pivotal** 2017-04-03 16:58 UTC

**Comment by tinygrasshopper** [comment] 2017-04-04 07:33
@dpb587-pivotal I think #1369 is a different issue, it refers to the old cli in which the you could not upload a blank cloud config (which I was under the impression was not maintained anymore). I am referring to the new CLI in which you can, but it breaks the director with the error I have documented above.

**Comment by dpb587-pivotal** [comment] 2017-04-06 15:28
They're both referring to not being able to update with an empty runtime-config (in the other issue, the cause happened to be they accidentally updated runtime-config instead of cloud-config, and then they were trying to clear out runtime-config). Since this is a director-level change, both CLIs would be affected.
