### ISSUE TITLE
Bosh team admins

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloudfoundry/bosh#1329] opened 2016-07-01 13:48 UTC
I have been experimenting with bosh uaa integration and bosh team admins and found an interesting issue.  I can define users to uaa and add them to team groups like `bosh.teams.team1.admin` which allows the following expected behaviors -  `bosh target`, `bosh login`, and `bosh deploy` but not `bosh ssh` on their deployments.  Turns out I had to add those users to `bosh.read` in order to be able to use `bosh ssh`.  Is this normal behavior for bosh teams?  I presumed that a user with a `*.admin` role would already have read permissions.   Thanks

**Comment by dpb587-pivotal** [comment] 2016-07-01 21:04
A user with `*.admin` should indeed have read permissions. But a `bosh.read` should not have SSH access.

Is it possible you were initially testing `bosh.teams.team1.admin` on an existing deployment that was created before your director supported teams? Deployments are only bound to specific teams during the first deploy, and previous director versions did not track that. If you then tested a new/recreated deployment with `bosh.teams.team1.admin` + `bosh.read`, I suspect SSH worked because the new deployment was correctly bound to the `team1` (and `bosh.read` didn't actually do anything). Possible?

**Comment by ChrisMcGowan** [comment] 2016-07-06 13:11
This was a brand new director I was testing with.  I created new users inside uaa for testing as follows:

`team11` - only membership was to `bosh.teams.team1.admin`
`team12` - only membership was to `bosh.teams.team1.admin`
`team21` - only membership was to `bosh.teams.team2.admin`
`team22` - only membership was to `bosh.teams.team2.admin`
`admin` - only membership was to `bosh.admin`
`readonly` - only membership was to `bosh.read`

Both `admin` and `readonly` worked as expected.  You are correct that the `readonly` account with `bosh.read` could not `bosh.ssh` into any deployments.

`team11` and `team21` where both used to deploy new test deployments on the director.  As expected `admin` can see all deployments/access all deployments.  Both `team11` and `team12` could only see the deployment done by user `team11` but neither could do a `bosh ssh` to that deployment.  `team21` and `team22` could only see the deployment done by `team21` and again could not `bosh ssh` into that deployment.

Here is a sample error on the `bosh ssh` command that lead me down he path to adding `bosh.read` to the `team11` user:
```
jumphost:~/projects$ bosh ssh
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'team11' on deployment 'shield14' on 'XXXX-microbosh'
Target deployment is 'shield14'

Setting up ssh artifacts

Director task 16
Error 600000: One of the following scopes is required to access this task: bosh.admin, bosh.1ca2a258-f9ca-494e-8452-d1ec112557cf.admin, bosh.read, bosh.1ca2a258-f9ca-494e-8452-d1ec112557cf.read
```

**Comment by cppforlife** [comment] 2016-07-07 03:36
@ChrisMcGowan not a normal behavior. 

> Turns out I had to add those users to bosh.read in order to be able to use bosh ssh. 

to clarify, once you've added `bosh.read`, you could use bosh ssh?

**Comment by ChrisMcGowan** [comment] 2016-07-07 13:27
Correct.  Once users where added to `bosh.read` they could then `bosh ssh` into their team based deployments.

**Comment by dpb587-pivotal** [comment] 2016-07-07 16:31
I'm kind of surprised the "expected scopes" does not include `bosh.teams.team1.admin` in the error message since the user that created `team11` deployment should have had that scope. Even more to see `*.read` listed.

I know you said a brand new director, but can you confirm which director version it's running?

**Comment by ChrisMcGowan** [comment] 2016-07-08 12:56
I started with a fresh director deployment using `256.2` and did the initial `team1` deployment  while on that release of the director and received the error in question.  I then upgraded the director at that time to `257.1`, logged out and back into the director and tried `bosh ssh` again and same result.  This was when I added the scope `bosh.read` to the test `team11` user.

**Comment by ChrisMcGowan** [comment] 2016-07-28 13:47
Just an update, I was able to re-create this issue on a different BOSH director currently at 256.2 with the same result. This test case was creating a new uaa user with just membership to `bosh.teams.testteam.admin`.  This user could login to the director and successfully deploy.  After the deployment, the test user was able to get a vm list from `bosh ssh` but after selecting a VM, the test user was denied access:
```
Director task 263405
Error 600000: One of the following scopes is required to access this task: bosh.admin, bosh.095aa975-c092-40c4-aa2a-2a5337a30353.admin, bosh.read, bosh.095aa975-c092-40c4-aa2a-2a5337a30353.read
```

Any updates on re-creating this bug and a possible fix?

Thanks

**Comment by cppforlife** [comment] 2016-08-01 19:05
@ChrisMcGowan investigating today...

**Comment by ChrisMcGowan** [comment] 2016-08-02 18:28
Thank you

**Comment by dpb587-pivotal** [comment] 2016-08-04 20:56
We were able to reproduce the issue. The `ssh` task is not properly propagating the deployment's teams so the SSH setup task could be not retrieved once started. Additionally, it looks like the "One of the following scopes..." message is currently showing an inaccurate message. Fixed on `develop` via https://github.com/cloudfoundry/bosh/commit/267be3ab5551864e3d05098f6b348b2b6c9a99f3.

**Comment by ChrisMcGowan** [comment] 2016-08-08 14:53
Thank You

**Comment by cppforlife** [comment] 2016-11-11 10:17
Closing. This was fixed in v258.

**Closed by cppforlife** 2016-11-11 10:17 UTC
Labels: problem
