### ISSUE TITLE
Bosh raises a deployment lock when two independent deployments occur

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh#1440] opened 2016-09-14 20:44 UTC
If two deployments are being deployed at the same time, but rely on a bosh-release common to both, it is possible to have a deployment fail because their compilation VMs will conflict:

```
Failed compiling packages > clamav/f713bfd84ee50fde128618f2867730bb6a5eb04a: Failed to acquire lock for lock:compile:889:72 uid: de215e37-02c0-4011-81a7-0b0f2d17c4b8 (00:15:00)
   Failed compiling packages (00:20:52)

Error 100: Failed to acquire lock for lock:compile:889:72 uid: de215e37-02c0-4011-81a7-0b0f2d17c4b8
```

It would be preferable to have Bosh logic say: "Bosh currently has compilation task X version Y scheduled and then hold the deployment until that task finishes" rather than thinking these are different

Since compiles are intended to be ephemeral, repeatable and generate the same artifacts, there isn't a good reason why two deployments could not share the same dependent compile job

**Comment by dpb587-pivotal** [comment] 2016-09-15 16:01
For what it's worth, BOSH does work this way - if a deployment sees the package is currently compiling it will wait (up to [15 minutes](https://github.com/cloudfoundry/bosh/blob/50a35c9c1e501bb0a5b696dbcd226b541e807614/bosh-director/lib/bosh/director/lock_helper.rb#L43-L43)) and then [re-check](https://github.com/cloudfoundry/bosh/blob/f10f6f9994d224021c6eadfd94a5621ce5183ad1/bosh-director/lib/bosh/director/deployment_plan/steps/package_compile_step.rb#L61-L61) if the package was compiled before attempting to compile the package itself.

It sounds like 15 minutes is not sufficient in your environment. It does seem reasonable to increase that hard-coded timeout since locks will automatically be reaped if a compilation process dies. Some packages can definitely take longer than 15 minutes to compile.

Do you have a suggestion on how long a deployment should block on some other deployment?

@cppforlife probably has some thoughts about this and if we'd be able to merge a PR with some sort of change.

**Comment by cppforlife** [comment] 2016-09-21 16:58
i wonder if we should remove timeout altogether.

**Comment by henryaj** [comment] 2018-05-09 09:05
We don't see this 15 minute timeout on our BOSH Lite environment - the deploy runs for 10–15 seconds before failing out. Any ideas as to why?

**Comment by gdenn** [comment] 2018-07-28 21:08
I just encountered the same problem. In our case we have an automation system that does BOSH deployments in parallel (three at the time). All of my three deployments used a new release of logstash and two of them failed with the get lock error message. The first deployments succeeded.

On our vSphere system with our compilation VMS we experience that compilation times for single releases often are above 15 minutes.

**Comment by jfmyers9** [comment] 2018-08-21 18:50
Closing and reopening this issue to force gitbot to create a story.

**Comment by jfmyers9** [comment] 2018-10-29 22:42
Hey all,

As @dpb587-pivotal pointed out, this should currently wait for up to 15 minutes before timing out on the compilation lock.

At this point in time, we consider this to be the expected behavior. We don't have a strong signal of what we should change the timeout to, and leaving the timeout unbounded could put us into situations where tasks are un-cancellable. Also, at this point we recommend that users use compiled to avoid unnecessary compilation of packages and improve the overall deployment experience.

Please feel free to reopen this issue if you have any more concerns or would like to discuss this further.

Best,

@jfmyers9 && @langered, CF BOSH

**Closed by jfmyers9** 2018-10-29 22:42 UTC
Labels: open-for-contribution, planned-enhancement, triaged, unscheduled

**Comment by jfmyers9** [comment] 2018-10-29 22:44
@henryaj,

It appears that you issue is slightly different as it deals with the release lock rather than the compiled package lock. It appears that we already have an issue open for this at https://github.com/cloudfoundry/bosh/issues/1995. Please feel free to continue the conversation there.

Best,

@jfmyers9 && @langered, CF BOSH
