### ISSUE TITLE
'bosh start' and 'bosh start --force' both fail

### ISSUE THREAD

**Issue by joshnn** [cloudfoundry/bosh#1227] opened 2016-04-19 18:54 UTC
My attempt to start all jobs fail with the error. Please help me how I can restore all jobs after 'bosh upload release' and then 'bosh deploy.'

```
$ bosh start
Acting as user 'admin' on deployment 'cf' on 'my-bosh'
You are about to start all jobs

Detecting deployment changes
----------------------------
Releases
No changes

Compilation
No changes

Update
No changes

Resource pools
small_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
small_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
medium_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
medium_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
large_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
large_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
runner_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
runner_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
router_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
router_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
small_errand
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
xlarge_errand
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4

Disk pools
No changes

Networks
No changes

Jobs
No changes

Properties
No changes

Cannot perform job management when other deployment changes are present. Please use `--force' to override.
{noformat}

{noformat}
$ bosh start --force
Acting as user 'admin' on deployment 'cf' on 'my-bosh'
You are about to start all jobs

Detecting deployment changes
----------------------------
Releases
No changes

Compilation
No changes

Update
No changes

Resource pools
small_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
small_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
medium_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
medium_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
large_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
large_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
runner_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
runner_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
router_z1
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
router_z2
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
small_errand
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4
xlarge_errand
  stemcell
    version type changed: String -> Float
      - 3215.4
      + 3215.4

Disk pools
No changes

Networks
No changes

Jobs
No changes

Properties
No changes

Start all jobs? (type 'yes' to continue): yes

Performing `start all jobs'...

Director task 129
  Started preparing deployment > Preparing deployment. Done (00:00:02)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started updating job consul_z2 > consul_z2/0 (-b362-4b91-9f31-463bd0206de2) (canary). Failed: `consul_z2/0 (-b362-4b91-9f31-463bd0206de2)' is not running after update. Review logs for failed jobs: consul_agent (00:10:10)

Error 400007: `consul_z2/0 (-b362-4b91-9f31-463bd0206de2)' is not running after update. Review logs for failed jobs: consul_agent

```

**Comment by voelzmo** [comment] 2016-04-20 07:40
@joshnn you can try to follow http://bosh.io/docs/tips.html#failed-job to figure out some more information why the consul job is failing.

**Comment by joshnn** [comment] 2016-04-29 16:43
Hi, what I see on my end with bosh instances --ps is:
{noformat}
 consul_z2/0 (-b362-4b91-9f31-463bd0206de2)*                     | failing | n/a | small_z2  | 10.10.80.37 |
|   consul_agent                                                             | unknown |     |           |            
|   metron_agent                                                             | running |     |           |            
{noformat}

What I found in consul_agent/consul_agent.stdout.log is agent repeating Graceful leave with an interval of about 60 seconds that end up error 400007. 

How can I tell what causes Graceful leave on consul_z2/0?

**Comment by ramonskie** [comment] 2016-08-16 09:22
solved this issue already?
because we face the same issue

**Comment by dpb587-pivotal** [comment] 2016-08-18 19:28
@ramonskie: might want to check if you have configured the correct number of consul agents. Perhaps look for `agent-client.is-last-node.result` in your logs to verify your values, and also double check that you have correctly configured your list of [consul.agent.servers.lan](http://bosh.io/jobs/consul_agent?source=github.com/cloudfoundry-incubator/consul-release&version=108#p=consul.agent.servers.lan).

**Comment by jbayer** [comment] 2016-08-29 21:11
i experienced a similar error recently. if you look at some [similar situations that pivotal cloud foundry customers have encountered](https://discuss.pivotal.io/hc/en-us/articles/218196687-Consul-fails-to-start-during-upgrade-in-PCF). talking with the engineers that work on cloud foundry and consul, they recommend:
* stopping the monit job in each consul VM `monit stop consul_agent`
* removing all the consul data under `rm -rf /var/vcap/store/consul_agent/*`
* after all VMs cleared of consul agent data, starting monit in each one

then it all came back for me.

**Comment by EdwardStudy** [comment] 2018-02-02 07:50
@jbayer It's work for me. But did we have any root cause of this consul agent failed?

**Comment by jbayer** [comment] 2018-02-02 08:29
consul can fail often. see here for failure recovery documentation: https://github.com/cloudfoundry-incubator/consul-release#failure-recovery

**Comment by dpb587-pivotal** [comment] 2018-02-02 18:08
Closing - these particular errors are release-specific, and the previous comments recommend useful links for resolving these issues and more.

**Closed by dpb587-pivotal** 2018-02-02 18:08 UTC
