### ISSUE TITLE
bosh-cli failed to tail bosh task log after 15 or 20 mins in a large deployment

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1926] opened 2018-04-05 01:13 UTC
We experienced a problem where bosh director returned 500 or 502 error sometimes when bosh-cli tailed the task log for awhile (like 15 or 20 mins) as below:

```
Task 4395811 processing
Capturing task '4395811' output:
  Getting task output:
    Director responded with non-successful status code '502' response '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
Exit code 1
```

But actually, the task is still running, so we still could tail the task when running `bosh task 4395811` again. This brought troublesome to our CI pipeline, the bosh-cli quit with 500 or 502 error, but the task was still running.  I saw the log from director_nginx:

```10.x.x.x - - [04/Apr/2018:13:27:37 +0000] "GET /tasks/4395811/output?type=event HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 11.952 11.952 .```

And saw the error msgs from director log:

```error.log:169248:2018/04/04 13:27:29 [error] 2350#0: *305714502 recv() failed (104: Connection reset by peer) while reading response header from upstream, cl
ient: 10.x.x.x, server: , request: "GET /tasks/4395811/output?type=event HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/4395811/output?type=event",
 host: "10.x.x.x:25555"
error.log:169322:2018/04/04 13:27:37 [error] 2351#0: *305716610 recv() failed (104: Connection reset by peer) while reading response header from upstream, cl
ient: 10.x.x.x, server: , request: "GET /tasks/4395811/output?type=event HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/4395811/output?type=event",
 host: "10.x.x.x:25555"
```

I suspect this problem has to do with the deployment size, it's a very large deployment containing thousands of VMs, we don't see such problem on a smaller deployment (like hundreds of VMs). The director version is 263.3.0.  We need to get it fixed to make our pipeline work well. Thanks.

/cc @maximilien

**Comment by cppforlife** [comment] 2018-04-05 23:01
> I suspect this problem has to do with the deployment size, it's a very large deployment containing thousands of VMs, we don't see such problem on a smaller deployment (like hundreds of VMs).

yeah typically we recommend to have many smaller deployments (with couple of hundred of vms).

> We experienced a problem where bosh director returned 500 or 502 error sometimes when bosh-cli 

can you see what's goign on in the debug logs. what is the process doing?

**Comment by cppforlife** [comment] 2018-04-05 23:01
cc @maximilien

**Comment by mattcui** [comment] 2018-04-06 04:01
@cppforlife The task actually ran well, so no error in task debug log. I think it's a performance problem, if it's not easy to solve on server side, possible to add retry logic in bosh-cli code? Thanks.

https://github.com/cloudfoundry/bosh-cli/blob/master/director/client_request.go#L236

**Comment by cppforlife** [comment] 2018-04-12 23:02
(asked IBM folks to try to add retry to CLI for 502 and see if it would be enough).

**Comment by mattcui** [comment] 2018-04-17 11:06
@cppforlife We added 502/500 error check in `bosh-utils` at https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/retry_clients.go#L47 :

```
if err != nil || ((resp.Request.Method == "GET" || resp.Request.Method == "HEAD") && (resp.StatusCode == http.StatusGatewayTimeout || resp.StatusCode == http.StatusServiceUnavailable || resp.StatusCode == http.StatusBadGateway || resp.StatusCode == http.StatusInternalServerError)) {
```

The test looked good, do you think if we could submit a PR to `bosh-utils` for the change? Thanks.

/cc @maximilien

**Comment by mattcui** [comment] 2018-04-20 11:57
We did see some issues when using community edition (v3.0.1) of bosh-cli, I will have some initial investigations, then I may raise the issue to the community if needed.

**Comment by mattcui** [comment] 2018-04-23 05:26
The problem I mentioned in above comment should be a [known issue](https://www.pivotaltracker.com/n/projects/956238/stories/155665285), we are going to increase `postgres.max_connections` to 200 in our environments. I will submit a PR to `bosh-utils` as I mentioned in https://github.com/cloudfoundry/bosh/issues/1926#issuecomment-381950666

/cc @cppforlife @maximilien

**Comment by cppforlife** [comment] 2018-05-02 01:08
@mattcui sounds like we can close this now.

**Closed by cppforlife** 2018-05-02 01:08 UTC

**Comment by bingosummer** [comment] 2018-06-08 09:37
I also hit the error when I run the pipeline `bosh-cpi-certification`. Not sure whether the root cause is same or not.
https://github.com/cloudfoundry-incubator/bosh-cpi-certification/blob/8f50361daed6d165897607cca658e932818a6bb4/shared/tasks/test-upgrade.sh#L45

bosh-cli `4.0.1` is used.

**Comment by bingosummer** [comment] 2018-06-17 18:06
Although I don't know why we get the error, but the fix for bosh-utils seems working for me.
