### ISSUE TITLE
bosh-azure-hyperv-centos-7-go_agent v3363.9 randomly fails in creating partitions in the ephemeral data disk

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/bosh#1605] opened 2017-03-02 00:56 UTC
**Issue Description:**
When creating VMs with bosh-azure-hyperv-centos-7-go_agent v3363.9, you may see below error.
```
Started compiling packages > batarang/dd553dce44383700de302954532220695c3fb912. Failed: Timed out pinging to 18e4f77e-d8b3-4d69-a6b3-f6b1974eeb80 after 600 seconds (00:14:34)
       
       Error 450002: Timed out pinging to 18e4f77e-d8b3-4d69-a6b3-f6b1974eeb80 after 600 seconds
```
After investigation, we find it failed in `blkid -p /dev/sdc1` after executing `parted` to create partitions in the ephemeral data disk. Although the commands `parted -s /dev/sdc unit B mkpart primary 1048576 14537457663` and `parted -s /dev/sdc unit B mkpart primary 14537457664 214747316223` returned `true`, the partitions were not created.
We never see this issue in older centos stemcell version and bosh-azure-hyperv-ubuntu-trusty-go_agent v3363.9.

**Logs:**
```
2017-02-28_03:46:42.52289 [linuxPlatform] 2017/02/28 03:46:42 INFO - Creating swap & ephemeral partitions on ephemeral disk...
2017-02-28_03:46:42.52290 [linuxPlatform] 2017/02/28 03:46:42 DEBUG - Getting device size of `/dev/sdc'
2017-02-28_03:46:42.52290 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'lsblk --nodeps -nb -o SIZE /dev/sdc'
2017-02-28_03:46:42.52575 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout: 214748364800
2017-02-28_03:46:42.52576 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr:
2017-02-28_03:46:42.52576 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)
2017-02-28_03:46:42.52576 [linuxPlatform] 2017/02/28 03:46:42 DEBUG - Calculating ephemeral disk partition sizes of `/dev/sdc' with total disk size 214748364800B
2017-02-28_03:46:42.52576 [linuxPlatform] 2017/02/28 03:46:42 INFO - Partitioning ephemeral disk `/dev/sdc' with [[Type: swap, SizeInBytes: 14536716288] [Type: linux, SizeInBytes: 200211648512]]
2017-02-28_03:46:42.52577 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'parted -m /dev/sdc unit B print'
2017-02-28_03:46:42.60075 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout:
                                                                         
BYT;

[7:13]  
2017-02-28_03:46:42.60077 /dev/sdc:214748364800B:scsi:512:512:unknown:Msft Virtual Disk:;
2017-02-28_03:46:42.60077 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr: Error: /dev/sdc: unrecognised disk label
2017-02-28_03:46:42.60077 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)
2017-02-28_03:46:42.60077 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'parted -s /dev/sdc mklabel gpt'
2017-02-28_03:46:42.62665 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout:
2017-02-28_03:46:42.62666 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr:
2017-02-28_03:46:42.62666 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)
2017-02-28_03:46:42.62666 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'parted -m /dev/sdc unit B print'
2017-02-28_03:46:42.64018 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout: BYT;
2017-02-28_03:46:42.64019 /dev/sdc:214748364800B:scsi:512:512:gpt:Msft Virtual Disk:;
2017-02-28_03:46:42.64020 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr:
2017-02-28_03:46:42.64020 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)
2017-02-28_03:46:42.64020 [attemptRetryStrategy] 2017/02/28 03:46:42 DEBUG - Making attempt #0
2017-02-28_03:46:42.64053 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'parted -s /dev/sdc unit B mkpart primary 1048576 14537457663'
2017-02-28_03:46:42.65987 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout:
2017-02-28_03:46:42.65988 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr:
2017-02-28_03:46:42.65988 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)

[7:13]  
2017-02-28_03:46:42.65988 [PartedPartitioner] 2017/02/28 03:46:42 INFO - Successfully created partition 0 on /dev/sdc
2017-02-28_03:46:42.65989 [PartedPartitioner] 2017/02/28 03:46:42 INFO - Partition 1 would be larger than remaining space. Reducing size to 200210907135B
2017-02-28_03:46:42.65989 [attemptRetryStrategy] 2017/02/28 03:46:42 DEBUG - Making attempt #0
2017-02-28_03:46:42.66019 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'parted -s /dev/sdc unit B mkpart primary 14537457664 214747316223'
2017-02-28_03:46:42.73690 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout:
2017-02-28_03:46:42.73691 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr:
2017-02-28_03:46:42.73691 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: true (0)
2017-02-28_03:46:42.73692 [PartedPartitioner] 2017/02/28 03:46:42 INFO - Successfully created partition 1 on /dev/sdc
2017-02-28_03:46:42.73692 [linuxPlatform] 2017/02/28 03:46:42 INFO - Formatting `/dev/sdc1' as swap
2017-02-28_03:46:42.73698 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Running command 'blkid -p /dev/sdc1'
2017-02-28_03:46:42.73796 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stdout:
2017-02-28_03:46:42.73797 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Stderr: error: /dev/sdc1: No such file or directory
2017-02-28_03:46:42.73798 [Cmd Runner] 2017/02/28 03:46:42 DEBUG - Successful: false (2)
2017-02-28_03:46:42.73798 [main] 2017/02/28 03:46:42 ERROR - App setup Running bootstrap: Setting up ephemeral disk: Formatting swap: Checking filesystem format of partition: Running command: 'blkid -p /dev/sdc1', stdout: '', stderr: 'error: /dev/sdc1: No such file or directory
2017-02-28_03:46:42.73798 ': exit status 2
2017-02-28_03:46:42.73798 [main] 2017/02/28 03:46:42 ERROR - Agent exited with error: Running bootstrap: Setting up ephemeral disk: Formatting swap: Checking filesystem format of partition: Running command: 'blkid -p /dev/sdc1', stdout: '', stderr: 'error: /dev/sdc1: No such file or directory
2017-02-28_03:46:42.73799 ': exit status 2
```

**Comment by cppforlife** [comment] 2017-03-02 01:26
current thinking is something on azure envs causes parted to not do anything. could be interesting to run strace?

**Comment by AbelHu** [comment] 2017-03-02 01:28
Will have a try to add `strace`

**Comment by dpb587-pivotal** [comment] 2017-04-20 00:20
@AbelHu, any findings on this?

**Comment by AbelHu** [comment] 2017-04-20 03:16
@dpb587-pivotal Now @bingosummer is tracking this issue. He may be able to answer your question.

**Comment by bingosummer** [comment] 2017-04-20 04:27
@dpb587-pivotal 

After partitioning the kernel needs to re-read the partition table, and then it will recreate the symlinks in /dev for each partition.  So there is a race here if bosh-agent moves too quickly. We are testing to sleep several seconds after partitioning. It seems working in 3363.9. But still need a verification to make sure it works every time.
If that's the root cause, the fix may be to add a small loop after partitioning to test and wait for the block device (i.e. /dev/sdc1) to exist, and then proceed with formatting. Do you think it makes sense?

**Comment by dpb587-pivotal** [comment] 2017-04-21 16:05
If that's the underlying issue, a short polling loop does seem like it makes sense. Thanks for the update.

**Comment by mfine30** [comment] 2018-08-28 19:18
Reading the issue, it looks like you found a way around. Due to the limited activity in the last year, I'm going to close this. If it is still an issue on more recent stemcell lines, please open a new updated issue.

**Closed by mfine30** 2018-08-28 19:18 UTC
Labels: problem
