### ISSUE TITLE
Can't modify frozen String from when bosh create release

### ISSUE THREAD

**Issue by YuPengZTE** [cloudfoundry/bosh#1342] opened 2016-07-08 07:13 UTC
Building dea_next...
  No artifact found for dea_next
  Generating...
  Pre-packaging...
  > + set -e -x
  > + cd /tmp/d20160708-18620-9ozhnm/d20160708-18620-1nfsvy3/dea_next
  > + gem install bundler -v 1.11.2
  > Successfully installed bundler-1.11.2
  > 1 gem installed
  > Installing ri documentation for bundler-1.11.2...
  > Installing RDoc documentation for bundler-1.11.2...
  > + BUNDLE_WITHOUT=development:test
  > + bundle _1.11.2_ package --all --no-install --path ./vendor/cache
  > Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
  > application for all non-root users on this machine.
  > Fetching gem metadata from https://rubygems.org/.........
  > Fetching version metadata from https://rubygems.org/..
  > Fetching https://github.com/cloudfoundry/warden.git
  > Fetching https://github.com/intridea/grape.git
  > Fetching https://github.com/cloudfoundry/loggregator_emitter.git
  > Fetching https://github.com/nats-io/ruby-nats.git
  > There was a RuntimeError while loading nats.gemspec:
  > can't modify frozen String from
  > /tmp/d20160708-18620-9ozhnm/d20160708-18620-1nfsvy3/dea_next/vendor/cache/ruby/1.9.1/bundler/gems/ruby-nats-d0556a0715c0/nats.gemspec:10:in
  > `block in <main>'
'dea_next' pre-packaging failed
root@agent-id-bosh-0:/home/vagrant/contribute/cf-release# bosh create release

**Comment by cppforlife** [comment] 2016-07-08 16:54
@YuPengZTE seems like the problem is coming from one of the pre_packaging script (for dea_next job) found in cf-release, not the cli itself.

**Comment by connected-ndey** [comment] 2016-07-14 18:41
I am experiencing the exact same problem as @YuPengZTE

**Comment by cppforlife** [comment] 2016-07-14 20:47
Moved to cf-release. Closing here.

**Closed by cppforlife** 2016-07-14 20:47 UTC
