### ISSUE TITLE
Certificate variable type does not add SSL client certificate purpose

### ISSUE THREAD

**Issue by sbourlon** [cloudfoundry/bosh#1965] opened 2018-05-26 01:25 UTC
Hi,

I think Bosh does not generate SSL client certificates correctly.

## Test 1:
When using the following certificate variable type:
```
    name: haproxy_client_ssl
    type: certificate
    options:
      ca: router_ca
      common_name: HAProxyClientSSL
      extended_key_usage:
      - server_auth
      - client_auth
```

The client certificate purposes does not have `SSL client: Yes`:
```
$ openssl x509 -in backend-crt.pem -text -noout -purpose
[...]
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
Netscape SSL server : Yes
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
```
## Test 2:
When using the following certificate variable type:
```
    name: haproxy_client_ssl
    type: certificate
    options:
      ca: router_ca
      common_name: HAProxyClientSSL
```

The client certificate purposes does not have `SSL client: Yes`:
```
$ openssl x509 -in backend-crt.pem -text -noout -purpose
[...]
Certificate purposes:
SSL client : No
SSL client CA : No
SSL server : Yes
SSL server CA : No
Netscape SSL server : Yes
Netscape SSL server CA : No
S/MIME signing : No
S/MIME signing CA : No
S/MIME encryption : No
S/MIME encryption CA : No
CRL signing : No
CRL signing CA : No
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : No
Time Stamp signing : No
Time Stamp signing CA : No
```
## Result:
The result of this misbehavior is the Gorouter in mTLS mode (Gorouter property `client_cert_validation: require`) does not accept the HAProxy client certificate by outputting the following error:
```
http: TLS handshake error from 10.244.0.150:43916: tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage
``` 

Thank you for your help!

**Comment by cppforlife** [comment] 2018-05-30 19:19
@sbourlon i checked with openssl command above certs that get generated when using --vars-store and they do show up as `SSL client : Yes`. are you using director + credhub or --vars-store. in either case we also do not currently support automatic regeneration of the certs if their options change, so my guess is your certs were generated before you had extended_key_usage and after you updated options they were not regenerated.

(267.x bosh release will include an option to regenerate if options change).

**Comment by sbourlon** [comment] 2018-05-31 01:02
Hi @cppforlife,

I used the following Bosh deploy command:
```
bosh -e vbox -d cf deploy cf-deployment.yml \
    -o operations/bosh-lite.yml \
    --vars-store deployment-vars.yml \
    -v system_domain=bosh-lite.com \
    -o operations/scale-to-one-az.yml \
    -o operations/use-compiled-releases.yml \
    -o operations/require-client-tls-certificates-for-gorouter.yml \
    -o operations/community/use-haproxy.yml`
```
where I added a certificate variable to `operations/community/use-haproxy.yml`.

If I understand correctly, I can't update a variable certificate? If that's the case, should I just destroy the deployment and redeploy?

Thank you for your help.

**Comment by cppforlife** [comment] 2018-05-31 20:54
`--vars-store deployment-vars.yml \` is what contains generated certs. you can edit deployment-vars.yml and remove section that represents certificate you want to delete. next time you run above command it will regenerate cert with new options.

**Comment by sbourlon** [comment] 2018-06-04 17:09
Thanks @cppforlife. It worked!

With:
```
      extended_key_usage:
        - server_auth
        - client_auth
```
The certificate will have the purpose:
```
SSL client : Yes
```

Should I close the issue or would you like to keep it to track an action item?

**Comment by cppforlife** [comment] 2018-06-04 23:06
> Should I close the issue or would you like to keep it to track an action item?

i dont think there is anything to do (given that you've verified that it actually works), but may be i misunderstood your request?

**Comment by dpb587-pivotal** [comment] 2018-06-08 13:43
Closing - sounds like the question was answered, and `extended_key_usage` and default behaviors are working as intended.

**Closed by dpb587-pivotal** 2018-06-08 13:43 UTC
