### ISSUE TITLE
bosh warden stemcell 3306 bash PS1 errors

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh#1506] opened 2016-11-10 19:27 UTC
I get the following bash errors when I ssh onto a bosh-lite vm
```
→ bosh ssh etcd_z1 0
Acting as user 'admin' on deployment 'etcd' on 'Bosh Lite Director'
Target deployment is 'etcd'

Setting up ssh artifacts

Director task 9

Task 9 done
Starting interactive shell on job etcd_z1/0
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-42-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Last login: Thu Nov 10 19:22:42 2016 from 192.168.50.1
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

cat: /var/vcap/instance/name: No such file or directory
cat: /var/vcap/instance/id: No such file or directory
/:~$ 
```

The issue is coming from the `00-bosh-ps1` file
```
/:~$ cat /etc/profile.d/00-bosh-ps1
#!/bin/sh

# only if interactive
[ ! -z "$PS1" ] || return

bosh_instance="$( cat /var/vcap/instance/name )/$( cat /var/vcap/instance/id )"

PS1="$bosh_instance:\\w\\\$ "

unset bosh_instance
```

Looks like there is no `/var/vcap/instance/` directory
```
/:~$ ll /var/vcap/
total 40
drwxr-xr-x 12 root root 4096 Nov 10 19:20 ./
drwxr-xr-x 15 root root 4096 Nov 10 19:13 ../
drwx------  8 root root 4096 Nov 10 19:15 bosh/
drwxr-xr-x  3 root root 4096 Nov 10 19:22 bosh_ssh/
drwxr-xr-x  7 root root 4096 Nov 10 19:15 data/
drwxr-xr-x  2 root root 4096 Nov 10 19:15 jobs/
drwxr-xr-x  3 root root 4096 Nov  7 18:25 micro_bosh/
drwxr-xr-x  6 root root 4096 Nov 10 19:15 monit/
drwxr-xr-x  2 root root 4096 Nov 10 19:15 packages/
drwxr-xr-x  4 root root 4096 Nov 10 19:15 store/
lrwxrwxrwx  1 root root   18 Nov 10 19:13 sys -> /var/vcap/data/sys/
```

**Comment by dpb587-pivotal** [comment] 2016-11-10 19:28
@zankich yup. currently there is a small diff between agent in other stemcells vs warden stemcell. planning to fix that shortly (or at least rebase temporarily to latest).

**Comment by liuweichu** [comment] 2016-11-28 06:29
@dpb587-pivotal Hi, we also encountered this problem.
We have another problem, that is we have our customized PS1 already but get overridden by `00-bosh-ps1`.

When fixing this, could you also update `bashrc` to check if `/etc/profile.d/00-bosh-ps1` exists before sourcing?

Means that the last 3 lines in [apply.sh](https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/bosh_users/apply.sh) change to: 

```
echo "[ -e /etc/profile.d/00-bosh-ps1 ] && source /etc/profile.d/00-bosh-ps1" >> $chroot/root/.bashrc
echo "[ -e /etc/profile.d/00-bosh-ps1 ] && source /etc/profile.d/00-bosh-ps1" >> $chroot/home/vcap/.bashrc
echo "[ -e /etc/profile.d/00-bosh-ps1 ] && source /etc/profile.d/00-bosh-ps1" >> $chroot/etc/skel/.bashrc
```

**Comment by dpb587-pivotal** [comment] 2016-11-28 16:28
@liuweichu, the file is installed at the stemcell level, so it should always be there.

Can you clarify how you are customizing PS1?

**Comment by liuweichu** [comment] 2016-11-29 00:46
We have our own [job](https://github.com/rakutentech/dotfiles-boshrelease) for doing that.

It might sound weird, our script is hooked on `.bash_aliases`.

Therefore, since 3306, the 00-bosh-ps1 will override our own settings, since it is the last line of `.bashrc`.

If the `[ -e ... ]` is added, we can safely delete the 00-bosh-ps1 script.

**Comment by dpb587-pivotal** [comment] 2016-11-29 00:51
@liuweichu, I'm not sure the stemcell should be adding conditionals for the files it is definitely installing. Instead of your job deleting the file, have you tried overwriting that file instead of `.bash_aliases` changes? Or tried emptying the `00-bosh-ps1` file?

**Comment by liuweichu** [comment] 2016-11-29 01:06
IMHO, check for existence before sourcing the script is generally more robust.
For example, this issue is exactly caused by `cat`ting non-existed considered-installed files.

**Comment by dpb587-pivotal** [comment] 2017-03-22 00:08
Closing - fixed in recent stemcells.

```
$ bosh upload-stemcell bosh-stemcell-3363.12-warden-boshlite-ubuntu-trusty-go_agent.tgz
$ bosh ssh
...snip...
Last login: Tue Mar 21 23:48:33 2017 from 192.168.50.1
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

minio/f77bb507-9e6b-4542-bc21-b610f4973402:~$
```

**Closed by dpb587-pivotal** 2017-03-22 00:08 UTC
Labels: problem
