### ISSUE TITLE
bosh v258 & v259 director process constantly uses 100% cpu

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/bosh#1491] opened 2016-10-25 11:54 UTC
After updating bosh from **v257.15** to **v258**, executing any task became very slow. I did some investigation and I found out that the process `/var/vcap/packages/director/bin/bosh-director -c /var/vcap/jobs/director/config/director.yml` was constantly using 100% cpu.
There are no tasks running, I double checked with `bosh tasks --no-filter`. The following is the output from `strace -f -c -p PID`

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 57.67    0.000947           0      5234           sendto
 23.20    0.000381           0      6628           poll
  9.99    0.000164           0     21858           clock_gettime
  5.91    0.000097           0      5258           write
  2.38    0.000039           0      7700       656 recvfrom
  0.85    0.000014           0      5472        42 stat
  0.00    0.000000           0        91        35 read
  0.00    0.000000           0        84           close
  0.00    0.000000           0        37           brk
  0.00    0.000000           0        42           writev
  0.00    0.000000           0       336           select
  0.00    0.000000           0        42           socket
  0.00    0.000000           0        81        39 accept
  0.00    0.000000           0       168           recvmsg
  0.00    0.000000           0        42         7 shutdown
  0.00    0.000000           0        42           bind
  0.00    0.000000           0        42           getsockname
  0.00    0.000000           0        42           getpeername
  0.00    0.000000           0        42           setsockopt
  0.00    0.000000           0        42           uname
  0.00    0.000000           0        84           fcntl
  0.00    0.000000           0       756           gettimeofday
------ ----------- ----------- --------- --------- ----------------
100.00    0.001642                 54123       779 total
```

PS: of course I tried to restart the process, to recreate the director vm, etc. I was able "to solve" the problem by going back to v257.15.

**Comment by paolostivanin** [comment] 2016-10-25 12:05
Output from `ltrace -f -c -p PID`:

```
% time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
 48.45   23.708106         149    158096 malloc_usable_size
 17.30    8.465422         150     56274 free
 11.55    5.652662         151     37407 malloc
  8.11    3.969524         150     26362 memcpy
  6.85    3.353998         149     22416 realloc
  6.00    2.935627         149     19582 calloc
  1.71    0.836083         149      5591 memmove
  0.03    0.012940         148        87 memset
------ ----------- ----------- --------- --------------------
100.00   48.934362                325815 total
```

**Comment by paolostivanin** [comment] 2016-10-25 12:19
After some minutes I did another check with strace:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 81.00    0.004017          10       413           select
 10.93    0.000542           0      7075           poll
  2.90    0.000144           0     23614           clock_gettime
  2.38    0.000118           0      5668           sendto
  1.11    0.000055           0      8396       743 recvfrom
  0.97    0.000048           0      5936        40 stat
  0.71    0.000035           0      5696           write
  0.00    0.000000           0        86        34 read
  0.00    0.000000           0        80           close
  0.00    0.000000           0        40           writev
  0.00    0.000000           0        40           socket
  0.00    0.000000           0        78        38 accept
  0.00    0.000000           0       160           recvmsg
  0.00    0.000000           0        40         6 shutdown
  0.00    0.000000           0        40           bind
  0.00    0.000000           0        40           getsockname
  0.00    0.000000           0        40           getpeername
  0.00    0.000000           0        40           setsockopt
  0.00    0.000000           0        40           uname
  0.00    0.000000           0        80           fcntl
  0.00    0.000000           0       906           gettimeofday
------ ----------- ----------- --------- --------- ----------------
100.00    0.004959                 58508       861 total
```

**Comment by dpb587-pivotal** [comment] 2016-10-25 15:21
Did anything show up in the director logs in `/var/vcap/sys/log/director/*.log`? Would also be curious to see what the memory usage of the running processes were.

**Comment by cppforlife** [comment] 2016-10-25 20:43
@paolostivanin hmm. we have a 258 director running and managing few deployments. cpu usage is regular. any more info about your env that you think may help?

**Comment by paolostivanin** [comment] 2016-10-26 06:15
@dpb587-pivotal no. Unfortunately, there's nothing interesting inside the logs. The following is the output of `ps -e -o %cpu,%mem,rss,vsz,command | grep director`

```
89.6  1.3 110592 212276 ruby /var/vcap/packages/director/bin/bosh-director -c /var/vcap/jobs/director/config/director.yml
 0.5  0.6 51640 151640 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_1.yml -i 1
 0.5  0.6 51712 151516 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_2.yml -i 2
 0.5  0.6 51580 151516 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_3.yml -i 3
 0.5  0.6 51664 151528 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_4.yml -i 4
 0.5  0.6 51564 151464 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_5.yml -i 5
 0.5  0.7 59156 158912 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_6.yml -i 6
 0.5  0.6 51508 151524 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_7.yml -i 7
 0.5  0.6 51416 151612 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_8.yml -i 8
 0.5  0.6 51552 151596 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_9.yml -i 9
 0.5  0.6 51804 151592 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_10.yml -i 10
 0.5  0.6 51580 151612 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_11.yml -i 11
 0.6  0.6 51500 151612 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_12.yml -i 12
 0.5  0.6 51460 151612 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_13.yml -i 13
 0.5  0.6 51312 151540 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_14.yml -i 14
 0.5  0.6 51604 151516 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_15.yml -i 15
 0.5  0.6 51536 151512 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_16.yml -i 16
 0.5  0.6 51404 151540 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_17.yml -i 17
 0.5  0.6 51456 151596 ruby /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_18.yml -i 18
 0.4  0.6 52228 218908 ruby /var/vcap/packages/director/bin/bosh-director-scheduler -c /var/vcap/jobs/director/config/scheduler.yml
```

@cppforlife we are running on Suse Cloud 6 on our own datacenter. The stemcell version is 3263.8 (also tested on a 3263.7 stemcell). If you need more info, just ask me :)

**Comment by JamesClonk** [comment] 2016-10-26 07:41
I can confirm this, we are seeing the same issue on bosh 258, also running latest stemcell 3263.8.
I also couldnt find anything special in the logs. No idea whats causing this. 😦 
We noticed this because we kept getting timeouts on director API GET calls.

**Comment by paolostivanin** [comment] 2016-10-26 08:24
@JamesClonk just for my curiosity, on which iaas are you running?

**Comment by tushar-dadlani** [comment] 2016-10-26 08:42
@paolostivanin We are running v258 with the following stemcell on an AWS env with the following stemcell : `bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3263.7`. We do not see this problem.

**Comment by paolostivanin** [comment] 2016-10-26 08:49
@tushar-dadlani thanks! Imma try it on our AWS env and I'll let you know! If @JamesClonk is using Openstack that it could be something  related to it...dunno!

**Comment by JamesClonk** [comment] 2016-10-26 08:57
@paolostivanin Yes, we're also running on Openstack.

**Comment by paolostivanin** [comment] 2016-10-26 09:27
I have just tested bosh 258 on our AWS deployment and it is working super fine. No problem at all on aws.
So this narrow down the issue on Openstack.
@tushar-dadlani do you have an OS env with which you could try bosh 258?

**Comment by tushar-dadlani** [comment] 2016-10-26 15:41
Unfortunately , we don't have any OpenStack environments.

**Comment by paolostivanin** [comment] 2016-10-27 08:43
@cppforlife to answer your slack request :) better pasting code here than there!
```
[pid 30015] select(17, [10 12 15 16], [15 16], [], {0, 0}) = 4 (in [15 16], out [15 16], left {0, 0})
[pid 30015] writev(15, [{"HTTP/1.1 200 OK\r\nContent-Type: t"..., 324}, {"[{\"name\":\"admin-ui\",\"releases\":["..., 4677}], 2) = 5001
[pid 30015] read(15, "", 16384)         = 0
[pid 30015] writev(16, [{"HTTP/1.1 200 OK\r\nContent-Type: t"..., 324}, {"[{\"name\":\"admin-ui\",\"releases\":["..., 4677}], 2) = 5001
[pid 30015] read(16, "", 16384)         = 0
[pid 30015] shutdown(15, SHUT_WR)       = -1 ENOTCONN (Transport endpoint is not connected)
[pid 30015] close(15)                   = 0
[pid 30015] shutdown(16, SHUT_WR)       = -1 ENOTCONN (Transport endpoint is not connected)
[pid 30015] close(16)                   = 0
[pid 30015] gettimeofday({1477554939, 730315}, NULL) = 0
[pid 30015] gettimeofday({1477554939, 730363}, NULL) = 0
[pid 30015] select(13, [10 12], [], [], {0, 90000}) = 0 (Timeout)
[pid 30015] gettimeofday({1477554939, 820718}, NULL) = 0
[pid 30015] gettimeofday({1477554939, 820801}, NULL) = 0
[pid 30015] select(13, [10 12], [], [], {0, 90000}) = 0 (Timeout)
[pid 30015] gettimeofday({1477554939, 911154}, NULL) = 0
[pid 30015] gettimeofday({1477554939, 911242}, NULL) = 0
[pid 30015] select(13, [10 12], [], [], {0, 90000}) = 0 (Timeout)
[pid 30015] gettimeofday({1477554940, 1821}, NULL) = 0
[pid 30015] gettimeofday({1477554940, 1900}, NULL) = 0
[pid 30015] select(13, [10 12], [], [], {0, 90000}) = 0 (Timeout)
[pid 30015] gettimeofday({1477554940, 92300}, NULL) = 0
```
I truncated the output but there were like tons of `select(13, [10 12], [], [], {0, 90000}) = 0 (Timeout)`

```
lsof -p 30015 -ad 10,12
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
ruby    30015 vcap   10r  FIFO   0,10      0t0 803493 pipe
ruby    30015 vcap   12u  IPv4 803494      0t0    TCP localhost:25556 (LISTEN)
```

**Comment by cppforlife** [comment] 2016-10-27 15:35
hmm. whats happening in the debug log of the director? also access logs?

**Comment by paolostivanin** [comment] 2016-10-28 06:35
Nothing interesting on the access log, just a bunch o:

```
"GET /deployments HTTP/1.1" 200 4677 "-" "EventMachine HttpClient" 0.055 0.055 .
"GET /deployments/cf-diego/instances HTTP/1.1" 200 1317 "-" "EventMachine HttpClient" 0.020 0.020 .
"GET /deployments/cf HTTP/1.1" 200 145994 "-" "HTTPClient/1.0 (2.7.1, ruby 2.3.1 (2016-04-26))" 0.008 0.008 .
"GET /info HTTP/1.1" 200 356 "-" "HTTPClient/1.0 (2.7.1, ruby 2.3.1 (2016-04-26))" 0.002 0.002 .
```

Inside the`debug` log file there are only some SQL stuffs, nothing interesting...

**Comment by cppforlife** [comment] 2016-10-28 23:59
@paolostivanin We think we know what's going on. `/deployments/cf-diego/instances` is doing some heavy lifting associated with `expects_vm`. we are not sure how many instances is too many but director definitely looks busy when that call happens. we'll dig into this first thing monday.

cc @voelzmo

**Comment by paolostivanin** [comment] 2016-10-31 07:15
@cppforlife good to know :) dunno if it could be helpful but currently we have 18 VMs running on Diego on our test system and 50 on our prod system

**Comment by voelzmo** [comment] 2016-10-31 07:56
@paolostivanin @cppforlife We'll look into it today: https://www.pivotaltracker.com/story/show/133419353

**Comment by JamesClonk** [comment] 2016-10-31 12:32
Maybe its not an Openstack problem, but of the bosh db?
We're not using postgres, but an external mariadb galera cluster to host the bosh db.

**Comment by paolostivanin** [comment] 2016-10-31 12:57
@JamesClonk we are using psql on both OS and AWS!

**Comment by beyhan** [comment] 2016-10-31 16:12
We can confirm that the issue is related to `expects_vm`. The implementation needs to create a deployment plan for this and apparently this operation is to expensive, when the manifests are rather big. Tomorrow is a public holiday in Germany and we will continue to work on a solution on Wednesday. So far we don't have an explanation why the issue doesn't occur on AWS.

**Comment by tushar-dadlani** [comment] 2016-10-31 16:22
@paolostivanin @beyhan @JamesClonk We have seen this issue on AWS as well. It depends on how many deployments you are running. The previous update was based on an environment with 2 deployments. We have seen this issue when the number of deployments increases.

**Comment by cppforlife** [comment] 2016-10-31 20:39
Story: https://www.pivotaltracker.com/story/show/133468217

**Comment by cppforlife** [comment] 2016-11-09 01:26
Fixed in v260. Thanks for letting us know.

**Closed by cppforlife** 2016-11-09 01:26 UTC
Labels: problem
