### ISSUE TITLE
Failure during `bosh deploy` can lead to incorrect link provider intents in the DB

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2025] opened 2018-08-13 09:30 UTC
Here is an error during a `bosh deploy -d cf` which lead to incorrect link provider intents in the database. Afterwards, we deployed something else that consumed links provided by CF, and the deployment *did not fail*, as there were the necessary provider intents in the database. However, the deployment didn't actually work, as there was no content in the links it rendered in the config.

[Here is a lengthy deploy debug log containing links DB updates and the failure of deploying CF](https://gist.github.com/voelzmo/82720f5ba8d1e0135bdca1dd7fc6515b)

**Comment by h4xnoodle** [comment] 2018-08-13 15:43
@voelzmo Hi Marco, thanks for your report.

It seems that BOSH is behaving by design here. 

Assuming we understand the issue: the only CF deployment attempted has failed. There have been link provider intents created. BOSH leaves any created intents behind during a failed deployment, to assist in debugging. A subsequent successful deployment will delete any unused links/providers at the end. Another deployment wishing to consume links from a failed deployment, will have no choice but to use the created links in the failed provider deployment.

We don't expect reliable behaviour for a cross-deployment consumer when the provider deployment has failed. 

Was there a successful deployment of `cf` after the failed one, and before attempting to consume again? 

What version of the director is being used?

**Comment by voelzmo** [comment] 2018-08-14 09:33
Is this a product feature?
> BOSH leaves any created intents behind during a failed deployment, to assist in debugging.
To me it seemed like something should have been rolled back, but wasn't.

This happened on Director Version: 266.6.0, I think this should also occur on the 267.x series, right?

**Comment by h4xnoodle** [comment] 2018-08-14 13:31
Yes @voelzmo as of 266.x we changed the behaviour. We felt that continuing to choose a set of links from a previous successful deployment could potentially hide more subtle problems with attempting to use old links. This behaviour will continue in future releases until otherwise.

In your case, the provider has failed, and there hasn't been a subsequent deployment that has succeeded. Would you still want to use the previously successful links, potentially incorrectly?

**Comment by h4xnoodle** [comment] 2018-08-15 18:56
Closing as this is currently by design.

**Closed by h4xnoodle** 2018-08-15 18:56 UTC
Labels: in progress
