### ISSUE TITLE
Deploy Bosh Fail on OpenStack (mirantis)

### ISSUE THREAD

**Issue by ngocvanho** [cloudfoundry/bosh#1757] opened 2017-08-10 12:28 UTC
Hi All,

I'm installing BOSH by bosh-init on my own OpenStack(deployed by mirantis). 

As my stdout below, it run to last step and failed because the director return with failing state.

tarted validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:24)
  Downloading release 'bosh-openstack-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:02)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:20)
Finished validating (00:00:47)

Started installing CPI
  Compiling package 'ruby_openstack_cpi/6576c0d52231e773f4ad53f5c5a0785c4247696a'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/918abecbb3015ee383d5cb2af23e8dbfed6392d1'... Finished (00:00:00)
  Installing packages... Finished (00:00:11)
  Rendering job templates... Finished (00:00:04)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:15)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-openstack-kvm-ubuntu-trusty-go_agent/3421.6'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM '7cd2ada0-142b-4ead-834d-abb36c8ffc6b'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:01)
  Unmounting disk 'd1aae540-8d9f-4b96-bf5b-2240728cec39'... Finished (00:00:07)
  Deleting VM '7cd2ada0-142b-4ead-834d-abb36c8ffc6b'... Finished (00:00:26)
  Creating VM for instance 'bosh/0' from stemcell '06ecf7c9-0b0a-44d1-a874-e5dc059938cb'... Finished (00:00:39)
  Waiting for the agent on VM '68cafca7-45a5-4009-9266-1cfac594f9cb' to be ready... Finished (00:03:40)
  Attaching disk 'd1aae540-8d9f-4b96-bf5b-2240728cec39' to VM '68cafca7-45a5-4009-9266-1cfac594f9cb'... Finished (00:00:30)
  Rendering job templates... Finished (00:01:06)
  Compiling package 'ruby_openstack_cpi/6576c0d52231e773f4ad53f5c5a0785c4247696a'... Finished (00:56:53)
  Compiling package 'ruby/c1086875b047d112e46756dcb63d8f19e63b3ac4'... Finished (00:57:14)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Finished (00:11:47)
  Compiling package 'libpq/661f5817afe24fa2f18946d2757bff63246b1d0d'... Finished (00:12:18)
  Compiling package 'bosh_openstack_cpi/918abecbb3015ee383d5cb2af23e8dbfed6392d1'... Finished (00:00:31)
  Compiling package 'registry/d81865cf0ad85fd79cb19aeb565bf622f2a17a83'... Finished (00:32:46)
  Compiling package 'postgres/3b1089109c074984577a0bac1b38018d7a2890ef'... Finished (00:55:06)
  Compiling package 'davcli/5f08f8d5ab3addd0e11171f739f072b107b30b8c'... Finished (00:00:05)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Finished (00:00:02)
  Compiling package 'health_monitor/e9317b2ad349f019e69261558afa587537f06f25'... Finished (00:30:39)
  Compiling package 'nginx/2ec2f63293bf6f544e95969bf5e5242bc226a800'... Finished (00:16:55)
  Compiling package 'nats/63ae42eb73527625307ff522fb402832b407321d'... Finished (00:03:00)
  Compiling package 's3cli/bb1c1976d221fdadf13a6bc873896cd5e2433580'... Finished (00:00:06)
  Compiling package 'director/50af678ba068312e5de229b0558775ebae8d0892'... Finished (00:38:38)
  Compiling package 'postgres-9.4/ded764a075ae7513d4718b7cf200642fdbf81ae4'... Finished (00:58:16)
  Updating instance 'bosh/0'... Finished (00:01:10)
  Waiting for instance 'bosh/0' to be running... Failed (00:10:31)
Failed deploying (06:33:13)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Received non-running job state: 'failing'

I logged to bosh vm, the "monit status" command return every service is fine except director_ctl. 

In monit log, I saw this line

[UTC Aug  9 18:36:50] info     : 'director' start: /var/vcap/jobs/director/bin/director_ctl
[UTC Aug  9 18:37:20] error    : 'director' failed to start

After I run monit stop , monit start and monit status. All service is running.

In bosh.ym, I'm using
- release
+ https://bosh.io/d/github.com/cloudfoundry/bosh?v=262.1
+ https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=32
- stemcell ubuntu 3421.6
+ https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3421.6
- Flavor
 + medium(4core, 8GB RAM)

I hope any one can help me solve this error. I spend almost a week for this and still hopeless.

Thank so much.

**Comment by dpb587-pivotal** [comment] 2017-08-10 16:06
Hi - can you take a look at the [job logs](http://bosh.io/docs/job-logs.html#vm-logs) for the `director` release job name? You should be able to find error messages or stacktraces of some sort which can help point out what the misconfiguration might be. If the errors you find there are unclear, please feel free to follow up.

**Comment by ngocvanho** [comment] 2017-08-14 07:02
[director.debug.log.txt](https://github.com/cloudfoundry/bosh/files/1221447/director.debug.log.txt)
[director.stderr.log.txt](https://github.com/cloudfoundry/bosh/files/1221448/director.stderr.log.txt)

Hi @dpb587-pivotal,
Please help me see the files that i attach above. I watched it but i understand errors.

**Comment by dpb587-pivotal** [comment] 2017-08-14 15:57
It doesn't look like there is anything wrong in the logs. Sometimes this can mean your VM is not fast enough. To verify this, you can try sshing onto the director after it comes up and check if `monit summary` shows all services as running (or check it after a short delay). If it is slow, you can try changing flavors or increase your [`*_watch_time`](http://bosh.io/docs/manifest-v2#update) settings in your deployment manifest.

I also see that your provisioning is taking ~6 hours - this isn't normal (it should take less than 30 minutes when compiling from source). This suggests your VM is underpowered (probably slow clock speed), or the network connectivity from your workstation to the VM is very slow.

**Comment by ngocvanho** [comment] 2017-08-15 02:02
Hi dpb587-pivotal

Thank for your attention.

My OpenStack,which was deployed by Mirantis, is running on 3 slave node(however, I must run 1 master node follow mirantis model) and all of node is VM of virtual box, which is running on PC with i7 processor, 32GB memory.

So I think because of too many layer of virtualization is the reason for OpenStackVM can't used up capacity of hardware. 

After I sent a reply yesterday, I ran bosh-init again with new flavor(4core, 8GB memory) but it take almost 11 hours to print out the failed like before(last flavor only take 6 hours).

So now, only 1 thing I can do is increase *_watch_time follow your suggestion. Hope it work

One again, thank a lots for your help.
Van

**Comment by ngocvanho** [comment] 2017-08-17 02:52
Hi dpb587-pivotal

I set  *_watch_time in bosh.yml as following 
------------------------------------------------
update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 5000-300000
  update_watch_time: 5000-300000
------------------------------------------------

■　The result is the same, but deployment time now cost 9 hours instead of 6 hours as before.

------------------------------------------------
Started deploying
  Creating VM for instance 'bosh/0' from stemcell '4feb6615-8db2-439d-9c7d-f38cecc57da0'... Finished (00:01:05)
  Waiting for the agent on VM 'afeff020-615f-4c94-b859-f1f254842f29' to be ready... Finished (00:06:09)
  Creating disk... Finished (00:00:22)
  Attaching disk '404dc9c4-5de5-48d3-852b-d5f4797360c2' to VM 'afeff020-615f-4c94-b859-f1f254842f29'... Finished (00:00:54)
  Rendering job templates... Finished (00:01:19)
  Compiling package 'ruby/c1086875b047d112e46756dcb63d8f19e63b3ac4'... Finished (01:24:03)
  Compiling package 'ruby_openstack_cpi/6576c0d52231e773f4ad53f5c5a0785c4247696a'... Finished (01:23:08)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Finished (00:17:21)
  Compiling package 'libpq/661f5817afe24fa2f18946d2757bff63246b1d0d'... Finished (00:19:39)
  Compiling package 'health_monitor/e9317b2ad349f019e69261558afa587537f06f25'... Finished (00:46:07)
  Compiling package 'postgres/3b1089109c074984577a0bac1b38018d7a2890ef'... Finished (01:12:34)
  Compiling package 'nginx/2ec2f63293bf6f544e95969bf5e5242bc226a800'... Finished (00:23:58)
  Compiling package 'davcli/5f08f8d5ab3addd0e11171f739f072b107b30b8c'... Finished (00:00:07)
  Compiling package 'nats/63ae42eb73527625307ff522fb402832b407321d'... Finished (00:04:08)
  Compiling package 's3cli/bb1c1976d221fdadf13a6bc873896cd5e2433580'... Finished (00:00:08)
  Compiling package 'bosh_openstack_cpi/918abecbb3015ee383d5cb2af23e8dbfed6392d1'... Finished (00:00:33)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Finished (00:00:05)
  Compiling package 'registry/d81865cf0ad85fd79cb19aeb565bf622f2a17a83'... Finished (00:47:52)
  Compiling package 'director/50af678ba068312e5de229b0558775ebae8d0892'... Finished (00:56:13)
  Compiling package 'postgres-9.4/ded764a075ae7513d4718b7cf200642fdbf81ae4'... Finished (01:13:58)
  Updating instance 'bosh/0'... Finished (00:01:10)
  Waiting for instance 'bosh/0' to be running... Failed (00:12:27)
Failed deploying (09:13:33)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Received non-running job state: 'failing'
------------------------------------------------
    
After the deployment ended with failure, I ssh to the bosh vm and run "monit start"

------------------------------------------------
/:/home/vcap# monit summary
The Monit daemon 5.2.5 uptime: 8h 49m 

Process 'nats'                      running
Process 'postgres'                  running
Process 'blobstore_nginx'           running
Process 'director'                  Execution failed
Process 'worker_1'                  running
Process 'worker_2'                  running
Process 'worker_3'                  running
Process 'director_scheduler'        running
Process 'director_nginx'            running
Process 'health_monitor'            running
Process 'registry'                  running
System 'system_localhost'           running
------------------------------------------------

Then I  start the directory manually, it seems being started normally

------------------------------------------------
/:/home/vcap# /var/vcap/jobs/director/bin/director_ctl start
/etc/sudoers: parsed OK
/etc/sudoers.d/README: parsed OK
/etc/sudoers.d/director: parsed OK
/:/home/vcap# monit summary
The Monit daemon 5.2.5 uptime: 8h 53m 

Process 'nats'                      running
Process 'postgres'                  running
Process 'blobstore_nginx'           running
Process 'director'                  running
Process 'worker_1'                  running
Process 'worker_2'                  running
Process 'worker_3'                  running
Process 'director_scheduler'        running
Process 'director_nginx'            running
Process 'health_monitor'            running
Process 'registry'                  running
System 'system_localhost'           running
------------------------------------------------
Question : 

1. Should I increase max-time for *_watch_time to 9 hours (the total of deployment time)? 
2. Is the "Waiting for instance 'bosh/0' to be running... Failed (00:12:27)"  the last step of "bosh-init deploy"?  
   If the director can come up by manual start, is it fine to continue use it? 

Thanks,
Van

**Comment by dpb587-pivotal** [comment] 2017-08-22 00:58
The max `*_watch_time` is separate from the total deploy time. You may want to increase it to 30 minutes to see if director eventually comes up cleanly.

If director comes up by manual start, it should generally work.

However... it sounds like your hardware may be too underpowered or there's some other virtualization misconfiguration which is causing these installation issues, and if that root cause is not resolved, you may experience issues later on which are even more difficult to diagnose. I'd recommend spending some time testing the performance of your setup outside of bosh.

**Comment by dpb587-pivotal** [comment] 2017-09-09 00:24
Closing - please feel free to follow up with more information about what you've found if you need more assistance.

**Closed by dpb587-pivotal** 2017-09-09 00:24 UTC
