### ISSUE TITLE
error in installing bosh_cli

### ISSUE THREAD

**Issue by chaitu554** [cloudfoundry/bosh#1029] opened 2015-11-17 06:05 UTC
can anyone provide me clear steps in installing ruby(1.9.3)version and bosh_cli ?

**Comment by allomov** [comment] 2015-11-17 06:52
As far as I understand this issue is duplicate of this one https://github.com/cloudfoundry/bosh/issues/1024 and can be removed

**Closed** 2015-11-17 21:12 UTC
