### ISSUE TITLE
Properties with null values don't appear in deploy diff

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1121] opened 2016-02-01 06:25 UTC
When a property has a null value, it doesn't seem to show up in the `bosh deploy` diff (whether the null value is being added, removed, or changed). It's a bit misleading when it then goes off to update and restart VMs.

```
properties:
  somehash:
    somekey: ~
```

When no other properties were changed, `bosh deploy` shows the following and then ends up updating VMs...

```
Properties
No changes
```

Noticed when using...
- `bosh/v250`
- `bosh-aws-cpi/v39`
- `aws-xen-hvm-ubuntu-trusty-go_agent/v3184.1`

**Comment by dpb587** [comment] 2016-02-02 13:11
The above happened with an older CLI which I didn't realize. I updated, but now I get new, odd behavior. It shows me the following on every deploy even though the manifest doesn't change. 

Now with a :sparkles:screenshot...

<img width="842" alt="screenshot" src="https://cloud.githubusercontent.com/assets/207601/12750299/1a427fee-c96b-11e5-991a-4e424f0c97ce.png">

    $ cat bosh.yml
    properties:
        consul:
            agent_config:
                advertise_addr: null
                bootstrap_expect: null
    
    $ bosh download manifest
    properties:
      consul:
        agent_config:
          advertise_addr: 
          bootstrap_expect:

**Comment by cppforlife** [comment] 2016-02-03 01:44
Associated story: https://www.pivotaltracker.com/story/show/112833065

**Comment by pivotal-devin-fallak** [comment] 2016-02-05 20:56
We can't reproduce this on the addons branch. Deployed a test job with a property with value of '~', then deployed again. No changes were printed.

**Comment by dpb587-pivotal** [comment] 2016-02-05 21:32
Strange - I guess I'll try again once addons are merged. I was seeing it on a couple deployments, but don't really have additional details. Thanks for the update.

**Comment by rwwohl** [comment] 2016-03-28 13:55
I'm also seeing this issue after upgrade to the latest bosh 255.6.  Every null value in my manifest shows up as a change even when nothing is changing:

properties:
  acceptance_tests: "<redacted>"
  app_ssh: "<redacted>"
  blobstore:
    admin_users: "<redacted>"
    secure_link:
      secret: "<redacted>"
    tls:
      cert: "<redacted>"
      private_key: "<redacted>"
....

This creates alot of noise making it difficult to see what actually is changing between deploys.

bosh cli version: 1.3215.0
bosh version: 255.6

For now, I'm dropping down to bosh version 246 which doesnt seem to have this issue

**Comment by dpb587** [comment] 2016-04-21 05:33
Seems fixed as of ~3215.3

**Comment by cdutra** [comment] 2017-10-19 20:59
Hi,

we're having the same issue with when updating cloud-config. We're using bosh cli version 2.0.44

Steps to reproduce:
1. Set cloud-config without the property you want to test.
```
...
vm_types:
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 4096
    nsxt:
      ns_groups: [no-access]
  name: no-access
...
```

2. Set the property you want to test with value `null`:
```
...
vm_types:
- cloud_properties:
    cpu: 2
    disk: 10240
    ram: 4096
    nsxt:
      ns_groups: [no-access]
      vif_type: null
  name: no-access
...
```

Diff won't show that the property was added however director will have the property with value `null`.

**Comment by dpb587-pivotal** [comment] 2017-10-20 17:14
Confirmed was able to reproduce with director 263.2...

```
$ cat cc.yml
vm_types:
- name: asdf
  cloud_properties:
    cpu: 123
    first: notnull
    second: null

$ gobosh update-cloud-config cc.yml
+ vm_types:
+ - cloud_properties:
+     cpu: 123
+     first: notnull
+     second:
+   name: asdf


$ cat cc.yml
vm_types:
- name: asdf
  cloud_properties:
    cpu: 123
    first: null
    second: notnull

$ gobosh update-cloud-config cc.yml
  vm_types:
  - name: asdf
    cloud_properties:
-     first: notnull
+     second: notnull
# TODO ^^^^^^^ first is still present, just null
# TODO ^^^^^^^ second was previously present, just null

$ cat cc.yml
vm_types:
- name: asdf
  cloud_properties:
    cpu: 123
    first: notnull
    second: null

$ gobosh update-cloud-config cc.yml
  vm_types:
  - name: asdf
    cloud_properties:
+     first: notnull
-     second: notnull
# TODO ^^^^^^^ first was previously present, just null
# TODO ^^^^^^^ second is still present, just null
```

**Comment by mfine30** [comment] 2018-08-07 19:12
Closing due to inactivity.

**Closed by mfine30** 2018-08-07 19:12 UTC
Labels: filed-as-story
