### ISSUE TITLE
 Is not it possible to correspond to proxy with authentication?

### ISSUE THREAD

**Issue by HiroshiFujita** [cloudfoundry/bosh#2005] opened 2018-07-17 05:19 UTC
https://github.com/cloudfoundry/bosh/blob/3b5c1fecfe38947650bec1b94cd0ce68b9cae749/src/bosh-director/lib/bosh/director/download_helper.rb#L22

With this code, ENV can solve only Proxy_Addr.
Do I need to set Proxy_Port, Proxy_ID, Proxy_Password as arguments?

https://docs.ruby-lang.org/en/2.5.0/Net/HTTP.html#method-c-start

**Comment by dpb587-pivotal** [comment] 2018-07-19 14:59
Closing as duplicate of #1842. It is not currently possible to use proxies that require authentication from the director. Feel free to continue discussion about this in that issue.

**Closed by dpb587-pivotal** 2018-07-19 14:59 UTC
