### ISSUE TITLE
bosh ssh should not connect successfully when given non-existent job index

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/bosh#922] opened 2015-08-15 00:03 UTC
**Actual Behavior:**  If I have only one vm: `job_z1/0` and I try to `bosh ssh job_z1 99` it will successfully connect to `job_z1/0`.

**Expected Behavior:**  I would expect it to fail and yell at me for trying to ssh into vm that doesn't exist. 

This can be confusing if I have jobs running across multiple AZs and accidentally increment the index instead of the AZ number.

cc @Amit-PivotalLabs

**Comment by uzzz** [comment] 2016-06-15 03:59
Looks like it already fixed

https://github.com/cloudfoundry/bosh/blob/master/bosh-director/spec/unit/api/instance_lookup_spec.rb#L58

**Comment by dpb587-pivotal** [comment] 2016-06-15 16:07
Closing - thanks, @uzzz, for mentioning this. Confirmed fixed.

    $ bo ssh dummy 99
    Acting as user 'admin' on deployment 'dummy' on 'director'
    Target deployment is 'dummy'
    
    Setting up ssh artifacts
    
    Director task 17
    Error 70001: No instances matched {:job=>"dummy", :index=>[99], :deployment_id=>1}
    
    Task 17 error
    Failed to set up SSH: see task 17 log for details

**Closed by dpb587-pivotal** 2016-06-15 16:07 UTC
Labels: open-for-contribution
