### ISSUE TITLE
Suggest to modify fog‘s check on response header

### ISSUE THREAD

**Issue by zhutao11** [cloudfoundry/bosh#1501] opened 2016-11-10 03:28 UTC
Background：
1. openstack version : Juno
2. bosh version：
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.14
  sha1: b41821dccee78ad7bd44466cd0160920c183787a
- name: bosh-openstack-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=27
  sha1: 85e6244978f775c888bbd303b874a2c158eb43c4`
3.Ruby version:2.2.3
4.bosh-init version: bosh-init-0.0.91-linux-amd64

issue:
1. Fail to deploy cloudfoundry
2.Workaround：
  Login in **Bosh-director VM** ，and the modify the code in "/var/vcap/packages/registry/gem_home/ruby/2.3.0/gems/fog-openstack-0.1.7/lib/fog/openstack/compute.rb"
Modifation: Insert a "#" to comment the code to check the responese header
`if !response.body.empty? && response.get_header('Content-Type') == 'application/json
    response.body = Fog::JSON.decode(respinse.body)
end`

Actually, the  "responese header" issue exists at multiple place in Fog's code.

Expectation：
My openstack API’s  response header must contains "Content-Type"=>"application/json; **charset=UTF-8**". I think is reasonable ,where “charset=UTF-8” contributes to response analysis. While the fog's check is too strick to  continue the CF deployment. 
So I need a help to solve this issue.
Thank you very much!!!

**Comment by cppforlife** [comment] 2016-11-10 03:58
cc @voelzmo any ideas why we are not seeing this? @zhutao11 who is your openstack provider?

**Comment by zhutao11** [comment] 2016-11-10 04:11
It's not the openstack's issue.  The response from openstack will be handled at Web Server,and the **UTF-8** in header comes from **Tomcat**.
I think the UTF-8 contributes to response analysis,  but should not be a limit.
Thank you very much!

**Comment by cppforlife** [comment] 2016-11-10 04:15
i see, given that this is something fog is doing this sounds that it needs to be adjusted in fog-openstack.

**Comment by voelzmo** [comment] 2016-11-10 07:52
This is a duplicate of https://github.com/cloudfoundry/bosh/issues/1495 – I already asked the same questions.

@zhutao11 If you have a webserver in the middle between OpenStack and your client make sure that it doesn't add `charset` to the content-type header. As already commented in https://github.com/cloudfoundry/bosh/issues/1495: nova has a test that there won't be a charset in the `content-type` answer: https://github.com/openstack/nova/blob/5158ca7dcffd583dc8dd7c29b0a9a595d7de7dcf/nova/tests/unit/api/openstack/test_wsgi.py#L63-L67

**Closed by voelzmo** 2016-11-10 07:52 UTC
Labels: problem
