### ISSUE TITLE
Is it expected to compile the ruby-2.4-r4 package twice when deploying director

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh#2063] opened 2018-10-11 04:14 UTC
The bosh release and bosh-azure-cpi-release vendor the same ruby package.
https://github.com/cloudfoundry/bosh/blob/master/packages/ruby-2.4-r4/spec.lock
https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/master/packages/ruby-2.4-r4/spec.lock

Expected: the ruby-2.4-r4 package is compiled once.
Actual: the ruby-2.4-r4 package is compiled twice.

```
  Rendering job templates... Finished (00:00:06)
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:02:15)
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:02:11)
  Compiling package 'mysql/898f50dde093c366a644964ccb308a5281c226de'... Finished (00:00:41)
  Compiling package 'libpq/0d118c5dd7928f8c057de40b5f8f2d7dde48f6c7'... Finished (00:00:23)
  Compiling package 'bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'golang/27413c6b5a88ea20a24a9eed74d4b090b7b88331'... Skipped [Package already compiled] (00:00:10)
  Compiling package 'gonats/73ec55f11c24dd7c02288cdffa24446023678cc2'... Finished (00:00:04)
  Compiling package 's3cli/3097f27cb9356172c9ae52de945821c4e338c87a'... Finished (00:00:04)
  Compiling package 'nginx/5a68865452a3bdcc233867edbbb59c1e18658f6b'... Finished (00:00:50)
  Compiling package 'postgres-9.4/b34d67da70e0295c09e4f4122e312f64e50896eb'... Finished (00:03:37)
```

**Comment by dpb587-pivotal** [comment] 2018-12-06 02:46
The CLI does not currently dedup these packages. The issue is a lower priority because it is typically less of a concern in environments where compiled releases are used for director which is what we use and recommend.

Closing since this is an issue in the bosh-cli - feel free to reopen there if you would like additional visibility on this or you want to continue the conversation there.

**Closed by dpb587-pivotal** 2018-12-06 02:46 UTC
Labels: unscheduled
