### ISSUE TITLE
Unable to deploy instances using T3 instances in AWS

### ISSUE THREAD

**Issue by jdesulme** [cloudfoundry/bosh#2135] opened 2019-02-08 21:29 UTC
**Describe the bug**
We're trying to deploy instances that were previously created as T2 instances to be T3 instances. A single line change of an existing working deployment manifest to an instance like t3.large fails with a timeout error trying to get the real device path. 

> Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdf

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on AWS with the bosh-deployment project
2. Upload ubuntu-xenial 
3. Deploy a basic simple nginx manifest with the instance configured as a t2.micro
4. This should deploy successfully 
5. Update the deployment manifests instance types to be a t3.large
6. Trying to deploy out this change results in a deployment failure 

**Expected behavior**
I would expect that I have the ability to change the instance to T3 and it just works 

```
Detecting deployment changes
----------------------------
resource_pools:
- name: default
  cloud_properties:
    instance_type: t2.micro
    instance_type: t3.large

compilation:
  cloud_properties:
    instance_type: t3.small
    instance_type: t3.large

Please review all changes carefully

Deploying
```

**Logs**
```
Task 3983 | 20:37:46 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 3983 | 20:37:46 | Preparing deployment: Preparing deployment (00:00:00)
Task 3983 | 20:37:47 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 3983 | 20:37:57 | Updating instance nginx: nginx/XXXXXX-77be-XXXXXX-XXXXXX-XXXXXX (0) (canary) (00:04:41)
                     L Error: Action Failed get_task: Task b0214a7f-3b06-400d-5da2-2e252cdd46eb result: Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdf
Task 3983 | 20:42:38 | Error: Action Failed get_task: Task b0214a7f-3b06-400d-5da2-2e252cdd46eb result: Mounting persistent disk: Getting real device path: Resolving mapped device path: Timed out getting real device path for /dev/sdf

Task 3983 Started  Fri Feb  8 20:37:46 UTC 2019
Task 3983 Finished Fri Feb  8 20:42:38 UTC 2019
Task 3983 Duration 00:04:52
Task 3983 error

Capturing task '3983' output:
  Expected task '3983' to succeed but state is 'error'
```

**Versions (please complete the following information):**
 - Infrastructure: AWS
 - BOSH version: 268.0.1 (00000000)
 - BOSH CLI version 5.4.0
 - Stemcell version: bosh-aws-xen-hvm-ubuntu-xenial-go_agent/250.4
-  Bosh release: [nginx/1.13.12](https://github.com/cloudfoundry-community/nginx-release/releases/tag/1.13.12)

**Deployment info:**
Bosh director originally deployed using the bosh-deployment project using config for AWS

**Comment by dpb587-pivotal** [comment] 2019-03-13 15:55
Closing as duplicate of #2128.

**Closed by dpb587-pivotal** 2019-03-13 15:55 UTC
Labels: unscheduled
