### ISSUE TITLE
Cannot upload release

### ISSUE THREAD

**Issue by bkez322** [cloudfoundry/bosh#1745] opened 2017-07-28 17:08 UTC
When I do `bosh upload release ~/Downloads/cf-mysql-release-36.tar.gz`

I get this error:

`Cannot find file '/var/folders/dx/3d4k2yp11d7_twlknf2r0vk80000gn/T/d20170728-25323-180oamt/d20170728-25323-3km3dd/release.MF'`

I see that https://github.com/cloudfoundry/bosh/issues/997 appears to reference this same issue. 

I am using the ruby bosh_cli gem on version 1.3262.26.0 (latest version), on ruby 2.3.0. My BOSH director is on version 262.3.0.

I am on Mac using default bsdtar.

**Comment by dpb587-pivotal** [comment] 2017-07-28 19:19
I'm not able to reproduce this locally - have you tried verifying the checksum of your download, or seeing if there's a different error emitted earlier in the output?

Alternatively, you may want to try the newer, [CLI v2](https://github.com/cloudfoundry/bosh-cli). The ruby CLI is deprecated, but in this particular use case it should be working without an issue.

**Comment by dpb587-pivotal** [comment] 2017-09-09 00:28
Closing - please feel free to follow up on this issue with the requested details if you need more help.

**Closed by dpb587-pivotal** 2017-09-09 00:28 UTC
