### ISSUE TITLE
`bosh stop` fails for a deployment with `lifecycle=nil` 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1937] opened 2018-04-13 14:47 UTC
BOSH version 265.1.0

During a deployment the director waits for all agents to start. If at this point a timeout happens the deployment fails. Such a deployment has `lifecycle=nil` and can't be deleted with `bosh delete-deployment` because the agents are in `unresponsive state`.  You can use `bosh delete-deployment --force` but VMs created by the IaaS will remain. Trying to delete the VMs with `bosh stop --hard` failed with:

```
E, [2018-04-13T12:14:13 #10841] [task:556950] ERROR -- DirectorJobRunner: no implicit conversion of nil into String
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/psych.rb:377:in `parse'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/psych.rb:325:in `parse'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/psych.rb:252:in `load'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:28:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-04-13T12:14:13 #10841] [task:556950] DEBUG -- DirectorJobRunner: (0.000427s) SELECT * FROM "tasks" WHERE ("id" = 556950) LIMIT 1
```

What worked in this situation is to use `bosh delete-vm` before `bosh delete-deployment`.

**Comment by cppforlife** [comment] 2018-04-13 15:35
> You can use bosh delete-deployment --force but VMs created by the IaaS will remain

did you dig into why that would be the case? delete deployment will call delete vm but sounds like ot receives some error.

**Comment by voelzmo** [comment] 2018-04-19 09:57
`delete-deployment` fails, because the agent can't execute `drain` and `stop` successfully

**Comment by jfmyers9** [comment] 2018-10-02 19:04
Hi @beyhan,

We tried recreating this behavior on our deployment and were unsuccessful. First we tried deleting a deployment with an unresponsive agent, and we saw that the VM was successfully deleted from the IAAS when using `bosh delete-deployment --force`. Then we tried setting the `lifecycle: nil` for the instance in question and once again saw that the VM was deleted from the IAAS when using the `--force` flag.

We are going to close this issue. If this is still a problem, please feel free to reopen the issue. If you could provide more specific steps to reproduce, that would also be helpful.

Best,

@jfmyers9 && @jaresty, CF BOSH

**Closed by jfmyers9** 2018-10-02 19:04 UTC
Labels: open-for-contribution, problem, triaged
