### ISSUE TITLE
[bosh cli] `bosh deploy` should return non zero code on "Error 430001: Could not reserve network for package compilation: capacity"

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudfoundry/bosh#767] opened 2015-03-03 11:18 UTC
`bosh deploy` should NOT return 0 if an exception `Error 430001: Could not reserve network for package compilation: capacity` occurs.

```
+ bosh -n --no-color --verbose deploy

Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...

Deploying
---------
Deployment name: `jenkins-enterprise-boshlite-aws.yml'
Director name: `Bosh Lite Director'

Director task 55
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)
     Done preparing deployment (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > ruby/f5fcaadde913f87b86119f6a652c4baab4a126a8
  Started compiling packages > jenkins-init-script/99ef661a8b75f7dbc5bea0cf202ef7cfcf5d9640
  Started compiling packages > cloudfoundry-cli/2c908a996c0bb41eb2cd95aca71f52b953b834b5
  Started compiling packages > golang/903eb898d8d3dc2452193139bcd1559aea3e7f74
   Failed compiling packages > ruby/f5fcaadde913f87b86119f6a652c4baab4a126a8: Could not reserve network for package compilation: capacity (00:00:00)
  Started compiling packages > git/6b9dd1fd95de8374c99fc37fd897668203ca8367
  Started compiling packages > maven/bd699a306a6adda723df5ee9656ff86bd42e33da
   Failed compiling packages > jenkins-init-script/99ef661a8b75f7dbc5bea0cf202ef7cfcf5d9640: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > cloudfoundry-cli/2c908a996c0bb41eb2cd95aca71f52b953b834b5: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > git/6b9dd1fd95de8374c99fc37fd897668203ca8367: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > golang/903eb898d8d3dc2452193139bcd1559aea3e7f74: Could not reserve network for package compilation: capacity (00:00:00)
   Failed compiling packages > maven/bd699a306a6adda723df5ee9656ff86bd42e33da: Could not reserve network for package compilation: capacity (00:00:00)

Error 430001: Could not reserve network for package compilation: capacity

Task 55 error

For a more detailed error report, run: bosh task 55 --debug
+ echo 'returned value '\''$?'\'': 0'
returned value '$?': 0
```

See `bosh task 55 --debug` at https://gist.github.com/cyrille-leclerc/c640670b3e4d0c6a13c5

**Comment by cppforlife** [comment] 2015-03-03 22:05
Are you using traveling-bosh? Some one was telling me that it always returns 0. /cc @drnic

**Comment by cyrille-leclerc** [comment] 2015-03-03 22:14
Indeed, I am using traveling bosh, it was installed this week so the version https://github.com/cloudfoundry-community/traveling-bosh/releases/tag/v1.2809.0

**Comment by JamesClonk** [comment] 2015-04-21 11:19
Hi,

I'm having the same issue, but with different error codes. I'm not using traveling-bosh though, but have it installed as a ruby gem.
It seems `bosh deploy` always returns with exitcode 0 even if there were errors during the deployment.

For example:
```
$ bosh deploy
Generating deployment manifest

Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...

Deploying
---------
Deployment name: 'cf.yml'
Director name: 'bosh'

Director task 11
  Started preparing deployment
  Started preparing deployment > Binding deployment. Done (00:00:00)
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Failed: 'router_z1/0' asked for a static IP 192.168.1.80 but it's already reserved/in use (00:00:00)
   Failed preparing deployment (00:00:00)

Error 130008: 'router_z1/0' asked for a static IP 192.168.1.80 but it's already reserved/in use

Task 11 error

For a more detailed error report, run: bosh task 11 --debug

$ echo $?
0
```


```
$ bosh version
BOSH 1.2922.0
```

**Comment by bosh-ci-push-pull** [comment] 2015-04-21 17:32
What's the output of `which bosh`?

**Comment by JamesClonk** [comment] 2015-04-21 22:55
I'm using rvm and bundler to handle my ruby env.
```
$ which bosh
~/.rvm/gems/ruby-2.2.1/bin/bosh
```

**Comment by dpb587-pivotal** [comment] 2016-11-04 15:48
Closing - I couldn't reproduce this in regular `bosh`, but we're also moving to a new go-based cli (dev currently happening in [cloudfoundry/bosh-cli](https://github.com/cloudfoundry/bosh-cli)) which handles exits much more reliably and hasn't seen this issue. Feel free to give gobosh a try and provide feedback in that repo. Thanks!

**Closed by dpb587-pivotal** 2016-11-04 15:48 UTC
Labels: open-for-contribution
