### ISSUE TITLE
bosh-init support macports openssl install on OSX or honor $PATH

### ISSUE THREAD

**Issue by mmessmore** [cloudfoundry/bosh#1284] opened 2016-06-01 15:21 UTC
Here's the error:

```
Command 'deploy' failed:
  Installing CPI:
    Compiling job package dependencies for installation:
      Compiling job package dependencies:
        Compiling package:
          Running command: 'bash -x packaging', stdout: 'OpenSSL version 1 or greater is required.
Currently available: OpenSSL 0.9.8zh 14 Jan 2016
', stderr: '+ set -e
++ PATH=/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin
++ openssl version
+ openssl_version='OpenSSL 0.9.8zh 14 Jan 2016'
++ echo OpenSSL 0.9.8zh 14 Jan 2016
++ cut -f2 '-d '
++ cut -f1 -d.
+ openssl_major_version=0
+ '[' 0 == 0 ']'
+ echo 'OpenSSL version 1 or greater is required.'
+ echo 'Currently available: OpenSSL 0.9.8zh 14 Jan 2016'
+ exit 1
```

Could /opt/local/bin be added to the PATH for openssl on OSX or can it just use my PATH as-is?

It's a nit, but it would be nice not to have to use a different packaging thing to install the same software in a different place.

-mike

**Comment by allomov** [comment] 2016-06-01 15:38
Hey, @mmessmore.

I believe this issue should be moved to [cloudfoundry-incubator/bosh-vsphere-cpi-release](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release) repo. Since the problem is in [these lines](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/packages/vsphere_cpi_ruby/packaging#L5). This is definitely not problem of BOSH project.

**Comment by dpb587-pivotal** [comment] 2016-06-02 00:51
@allomov, fwiw the same potential problem code is in [aws-cpi](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/packages/ruby_aws_cpi/packaging), not just [vsphere-cpi](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/packages/vsphere_cpi_ruby/packaging).

**Comment by mfine30** [comment] 2018-08-15 18:47
I believe this has been fixed in more recent versions. However, if this is still an issue, could you please open an issue in https://github.com/cloudfoundry/bosh-cli.

**Closed by mfine30** 2018-08-15 18:47 UTC
