### ISSUE TITLE
stemcell building vm user's uid is 900 - 1000 expected

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry/bosh#971] opened 2015-10-10 09:00 UTC
When you build stemcell locally you get an error saying that user's uid should be 1000, currently it is 900.

**Comment by voelzmo** [comment] 2015-10-11 02:18
Duplicate of https://github.com/cloudfoundry/bosh/issues/807. Closing this one.

**Closed by voelzmo** 2015-10-11 02:18 UTC
