### ISSUE TITLE
CFCR(Cloud foundry container runtime) auto scaling(horizontal and vertical) by BOSH command on cluster level

### ISSUE THREAD

**Issue by mukeshrajmca** [cloudfoundry/bosh#1954] opened 2018-05-14 10:59 UTC
Hi everyone,

We are using CFCR(Cloud foundry container runtime), so can we perform auto scaling(horizontal and vertical) by BOSH command on cluster level(Based on some metrics) not on application level. Application level auto scaling can be achieved by kubectl command itself or kubernetes dashboard.

**Comment by cppforlife** [comment] 2018-05-22 00:26
@mukeshrajmca bosh core itself is not planning to add auto scaling functionality, however, one can build automation on top of existing bosh apis to do horizontal and vertical autoscaling. our hope is that an open source implementation emerges based on agreed upon conventions. if you are interested describing your specific use case, please head over here: https://github.com/cloudfoundry/bosh-notes/issues/32

**Comment by jfmyers9** [comment] 2018-10-02 19:07
Closing as a duplicate of https://github.com/cloudfoundry/bosh/issues/1652. Please redirect any further comments to that issue.

Best,

@jfmyers9 && @jaresty, CF BOSH

**Closed by jfmyers9** 2018-10-02 19:07 UTC
Labels: discuss, open-for-contribution, triaged
