### ISSUE TITLE
Deploy stops and says it succeeded before actually creating all desired instances

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1981] opened 2018-06-17 00:25 UTC
I have a deployment with an instance group with 3 desired instances.  I deployed successfully, then manually deleted two of the VMs from the IaaS console.  I `bosh ignore`d the remaining instance, and then re-ran `bosh deploy` expecting it to converge to the desired state of having 3 instances.  The deploy "succeeded" but only created one new instance.  Only after unignoring the previously-ignored VM did the next run of `bosh deploy` create the third desired instance.

Not sure if these things matter but some additional facts about the setup:
* after deleting the two VMs, I added their IPs the reserved IPs in the cloud config, and updated cloud config (to force selecting new IPs, as part of an experiment)
* after deleting the two VMs, whenever I ran `bosh deploy` I used the `--fix` flag otherwise it would fail early trying to get state of the missing VMs
* the instance group had 3 AZs
* the ignored instance was _not_ the bootstrap instance

I can get task logs, config files, versions, etc. and anything else that might help, just let me know what would be useful and I can DM them.

**Comment by pivotal-jamil-shamy** [comment] 2018-06-19 13:48
[Pivotal tracker story](https://www.pivotaltracker.com/story/show/158461015) for investigation.

**Comment by belinda-liu** [comment] 2018-11-20 22:04
Hey Amit,

We tried to reproduce the scenario but didn't see the same failure. Below is the output, you can see that after redeploying all three instances are running successfully. We experimented with various configurations with different azs, ignoring different instances, and updating the reserved IPs in the cloud config and still weren't able to reproduce the issue. 
 
```
jm+bl $ bosh -d zookeeper instances --details
Using environment '192.168.50.6' as client 'admin'

Task 12. Done

Deployment 'zookeeper'

Instance                                        Process State  AZ  IPs         State    VM CID                                VM Type  Disk CIDs                             Agent ID                              Index  Resurrection  Bootstrap  Ignore
                                                                                                                                                                                                                          Paused
zookeeper/438fd82a-7241-4df7-b4ea-6fb62891f9ac  running        z1  10.244.0.2  started  9805f023-63f6-4cfa-7691-62209f292238  default  fd3abd2d-04cc-467a-4a20-e99bdba0016c  244eb05e-ac27-48e8-ba3c-d04a8b324b63  0      false         true       false
zookeeper/59debd80-5367-418d-bf69-e1ecbad7363a  running        z3  10.244.0.4  started  e92d9289-2afd-4500-56ef-0584cd5f7f08  default  ffcc3e28-7bcb-47fa-7f04-b42db6dabe39  13e1034b-0e06-49d4-9bfc-4234dbe767f3  2      false         false      false
zookeeper/c2dac497-de71-4f29-b8eb-68b7f1970a16  running        z2  10.244.0.3  started  df7fbaa1-5dec-4bc0-56dc-e6119e7ef434  default  6ad2c63d-fd54-42d1-6ec4-5a06ba5dcf37  85114aa4-7429-4972-8316-06815a3e0d0d  1      false         false      false

3 instances

Succeeded
2018-11-20 13:47 ~/deployments/vbox
jm+bl $ bosh vms
Using environment '192.168.50.6' as client 'admin'

Task 13. Done

Deployment 'zookeeper'

Instance                                        Process State       AZ  IPs         VM CID                                VM Type  Active
zookeeper/438fd82a-7241-4df7-b4ea-6fb62891f9ac  unresponsive agent  z1  10.244.0.2  9805f023-63f6-4cfa-7691-62209f292238  default  true
zookeeper/59debd80-5367-418d-bf69-e1ecbad7363a  unresponsive agent  z3  10.244.0.4  e92d9289-2afd-4500-56ef-0584cd5f7f08  default  true
zookeeper/c2dac497-de71-4f29-b8eb-68b7f1970a16  running             z2  10.244.0.3  df7fbaa1-5dec-4bc0-56dc-e6119e7ef434  default  true

3 vms

Succeeded
2018-11-20 13:48 ~/deployments/vbox
jm+bl $ bosh -d zookeeper ignore zookeeper/c2dac497-de71-4f29-b8eb-68b7f1970a16
Using environment '192.168.50.6' as client 'admin'

Using deployment 'zookeeper'

Succeeded
2018-11-20 13:48 ~/deployments/vbox
jm+bl $ bosh -d zookeeper deploy zookeeper.yml --fix
Using environment '192.168.50.6' as client 'admin'

Using deployment 'zookeeper'

Release 'zookeeper/0.0.9' already exists.

Continue? [yN]: y

Task 14

Task 14 | 21:48:50 | Preparing deployment: Preparing deployment (00:02:15)
Task 14 | 21:51:05 | Warning: You have ignored instances. They will not be changed.
Task 14 | 21:51:05 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 14 | 21:51:15 | Updating instance zookeeper: zookeeper/438fd82a-7241-4df7-b4ea-6fb62891f9ac (0) (canary) (00:00:28)
Task 14 | 21:51:43 | Updating instance zookeeper: zookeeper/59debd80-5367-418d-bf69-e1ecbad7363a (2) (00:00:17)

Task 14 Started  Tue Nov 20 21:48:50 UTC 2018
Task 14 Finished Tue Nov 20 21:52:00 UTC 2018
Task 14 Duration 00:03:10
Task 14 done

Succeeded
2018-11-20 13:52 ~/deployments/vbox
jm+bl $ bosh vms
Using environment '192.168.50.6' as client 'admin'

Task 15. Done

Deployment 'zookeeper'

Instance                                        Process State  AZ  IPs         VM CID                                VM Type  Active
zookeeper/438fd82a-7241-4df7-b4ea-6fb62891f9ac  running        z1  10.244.0.2  b2733259-660f-4a7f-67ff-ea38b1cb7bed  default  true
zookeeper/59debd80-5367-418d-bf69-e1ecbad7363a  running        z3  10.244.0.4  ac27805c-5a29-442f-58f7-2cc33be1d7f1  default  true
zookeeper/c2dac497-de71-4f29-b8eb-68b7f1970a16  running        z2  10.244.0.3  df7fbaa1-5dec-4bc0-56dc-e6119e7ef434  default  true

3 vms

Succeeded
```

We've fixed a couple of issues around ignored instances since this issue was opened, so the behavior in this situation may have changed. We're going to close this issue, feel free to reopen if it happens again.

Thanks,
@belinda-liu && @jfmyers9, CF BOSH

**Closed by belinda-liu** 2018-11-20 22:04 UTC
