### ISSUE TITLE
errand deployment error: Can't generate network settings without an IP

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1639] opened 2017-03-26 23:34 UTC
```
  instance_groups:
+ - azs:
+   - z1
+   instances: 1
+   jobs:
+   - name: broker-deregistrar
+     release: broker-registrar
+   lifecycle: errand
+   name: broker-deregistrar
+   networks:
+   - name: default
+   stemcell: default
+   vm_type: default
Task 1956

23:31:11 | Preparing deployment: Preparing deployment (00:00:00)
            L Error: Can't generate network settings without an IP
```

When I add this errand to my deployment I get an internal director error. I found it inside bosh src but its not obvious what the root cause is.

Note, the errand above is one of two; the deployment works with `broker-registrar` errand but not both.

The `default` network is huge and has lots of IPs remaining.

Suggestions for debugging?

**Update:** the failing `broker-deregistrar` errand consumes a link provided by the other errand `broker-registrar` - https://github.com/cloudfoundry-community/broker-registrar-boshrelease/tree/links-and-cloud-config/jobs

**Comment by drnic** [comment] 2017-03-28 04:06
This issue did not reproduce itself today. Don't know what changed. 😕

**Comment by drnic** [comment] 2017-03-28 04:43
I can reproduce this.

```
git clone github.com/cloudfoundry-community/broker-registrar-boshrelease -b links-and-cloud-config
bosh2 create-release && bosh2 upload-release

export BOSH_DEPLOYMENT=broker-registrar-demo
bosh2 -n deploy manifests/failing-test.yml
```

**Comment by miyer-pivotal** [comment] 2017-04-25 20:37
I'm hitting the exact same issue with a broker-deregistrar errand - since the last update, were you able to figure out the root cause?

**Comment by drnic** [comment] 2017-04-25 23:57
@miyer-pivotal the discussion on this issue stoppped so I moved away from links for sharing this info between two errands and am duplicating the properties on both errands

**Comment by Lafunamor** [comment] 2017-05-17 14:53
I just ran in this issue. It seems like errands can not provide links or consume link provided by themselves.

I suggest adding at least a meaningful error message for this case. "Can't generate network settings without an IP" is very difficult to trouble shoot.

I generally don't see the need for errand to be able to provide links as they are short lived. If an errand has a dependency on an other errand, they probably should be merged into one errand.

**Comment by wfernandes** [comment] 2017-10-31 15:48
We ran into this issue on the `notifications-release`. We were trying to deploy with [this PR](https://github.com/cloudfoundry-incubator/notifications-release/pull/22) which includes bosh-links.
I'm assuming this issue has not yet been resolved.

**Comment by jasonkeene** [comment] 2018-02-12 17:29
I ran into this issue as well.

I was making a change to the Loggregator acceptance tests to use links vs properties. Loggregator is deployed as it's own deployment and the acceptance tests errand is a separate deployment that consumes links for the locations of the endpoints for Loggregator (metron agent, rlp, and trafficcontroller). The metron agents deployed with Loggregator only listen on `localhost` so we can't talk over the network to them. To get around this we colocate a metron agent on the acceptance tests errand's instance group. It would be nice to allow the errand to consume links from jobs in its own instance group for ports, certs, etc.

**Comment by aeijdenberg** [comment] 2018-06-12 03:48
@drnic - we've hit this error today. I note the other thing that changed for us this morning is a new version of `bosh-deployment` which appears to have added a lot of new error checks for link related stuff, so it may be a likely culprit.

https://github.com/cloudfoundry/bosh/releases/tag/v266.2.0 (e.g. caused https://github.com/cloudfoundry/cf-deployment/pull/525)

**Comment by aeijdenberg** [comment] 2018-06-12 12:56
I was able to workaround this by removing the `sanity-test` instance group for the `docker-broker` - we weren't using it anyway, and it seemed to be triggering the error.

**Comment by jfmyers9** [comment] 2018-09-13 17:52
This is a duplicate of https://github.com/cloudfoundry/bosh/issues/2033. We have fixed this in the latest BOSH release.

Feel free to reopen / create a new issue if you are still seeing issues.

**Closed by jfmyers9** 2018-09-13 17:52 UTC
Labels: discuss, feature:links
