### ISSUE TITLE
Feature request: target bosh deployment by name

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/bosh#1336] opened 2016-07-06 19:40 UTC
Currently I can do `bosh download manifest foo /tmp/foo.yml && bosh deployment /tmp/foo.yml` to target a deployment (to ssh in, for instance). It'd be much nicer if I could just `bosh deployment foo`, or `bosh deployment --name foo`.

**Comment by dpb587-pivotal** [comment] 2016-07-07 22:15
Thanks for feedback! This is a duplicate of #1312 so I'll close and link this, but feel free to add any additional thoughts on that issue.

**Closed by dpb587-pivotal** 2016-07-07 22:15 UTC
Labels: planned-enhancement
