### ISSUE TITLE
bosh upload does not use http_proxy environment variables

### ISSUE THREAD

**Issue by ibrahimwu** [cloudfoundry/bosh#1479] opened 2016-10-18 03:37 UTC
When running a bosh upload on a director that is behind a proxy, the following errors occur

>I, [2016-10-18 03:28:06 #26855] [task:6]  INFO -- DirectorJobRunner: Downloading remote release from https://bosh.io/d/github.com/cloudfoundry/cf-release
>E, [2016-10-18 03:28:26 #26855] [task:6] ERROR -- DirectorJobRunner: Downloading remote release from https://bosh.io/d/github.com/cloudfoundry/cf-release failed: #\<SocketError: Failed to open TCP connection to bosh.io:443 (getaddrinfo: Name or service not known)\>

This is despite the corresponding env parameters have been set in the director manifest as well as verified that it has been set in the director VM using command
`sudo cat /proc/$(pgrep -f bosh-director-worker -n)/environ | xargs -0n1 | grep -i prox`

A check on on [download_helper.rb](https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/download_helper.rb#L16) seem to indicate that proxy is not set. According to the [apidock](http://apidock.com/ruby/Net/HTTP/Proxy/class), net/http does not use the HTTP_PROXY and requires to be set explicitly

**Comment by dpb587-pivotal** [comment] 2016-10-18 23:59
Thanks for looking into the issue! Looks like this is a duplicate of PR #1461, so I'll close this in favor of having further discussion in a single place. You could also try out that patch if you needed to make some progress in the meantime.

**Closed by dpb587-pivotal** 2016-10-18 23:59 UTC
