### ISSUE TITLE
cloudconfig without network section causes metrics server to fail to start

### ISSUE THREAD

**Issue by moritzfalke** [cloudfoundry/bosh#2237] opened 2020-02-13 11:11 UTC
**Describe the bug**
The metrics server throws an exception when a cloud config without network section is uploaded. In addition, if a director is recreated with such a cloud config, the metrics server job fails to start.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director (Version v270.11.0) on virtualbox with metrics server ops file
2. Upload cloud config without network section
```
disk_types:
  - disk_size: 120000
     name: test
```
3. ssh onto the director
4. query metrics with
`curl http://localhost:9092/metrics`
5. See exception thrown in:
/var/vcap/sys/log/director/metrics_server.stderr.log

Alternatively, recreate the director after uploading the cloud config. This causes the metrics server to fail to start.

**Expected behavior**
no exception

**Logs**
File: /var/vcap/sys/log/director/metrics_server.stderr.log
```
 47343955214380 rufus-scheduler intercepted an error:
  47343955214380   job:
  47343955214380     Rufus::Scheduler::IntervalJob "30s" {}
  47343955214380   error:
  47343955214380     47343955214380
  47343955214380     Bosh::Director::ValidationMissingField
  47343955214380     Required property 'networks' was not specified in object ({"disk_types"=>[{"disk_size"=>120000, "name"=>"test"}]})
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/validation_helper.rb:16:in `safe_property'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:48:in `parse_networks'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:14:in `parse'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:127:in `block in populate_network_metrics'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:126:in `map'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:126:in `populate_network_metrics'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:105:in `populate_metrics'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:54:in `block in start'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:223:in `do_call'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:267:in `trigger_now'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:312:in `block (3 levels) in start_work_thread'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:315:in `block (2 levels) in start_work_thread'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `loop'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:301:in `block in start_work_thread'
  47343955214380       /var/vcap/data/packages/director/1945d30775477aadc066dbcaade169aa6a960cfc/gem_home/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Versions (please complete the following information):**
 - Infrastructure: any
 - BOSH version 270.11.0

**Additional context**
This seems to have been introduced with commit: https://github.com/cloudfoundry/bosh/commit/699d5fa73be661e2187fc1eeadf2cbe66eb09ab3
In this line it iterates over all cloud configs and requires them to have a network section when accessing the network property https://github.com/cloudfoundry/bosh/blob/de77df94368f6e6b06860b16af39e14dee0a03f7/src/bosh-director/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb#L48

This also happens if multiple cloud configs are uploaded and only one of them does not have a network defined.

cc @BeckerMax

**Comment by h4xnoodle** [comment] 2020-02-13 18:47
Hi @moritzfalke while we acknowledge the bug and I'll shortly submit a fix, the cloud config technically lists `networks` as required here https://bosh.io/docs/cloud-config/#networks. 

In most use cases `networks` is generally required to deploy anything. In your case here, which I would argue may not be the most useful, networks aren't used since we don't have validation when there isn't a deployment, it isn't apparent that `networks` are required.

**Comment by BeckerMax** [comment] 2020-02-13 20:16
Hi @h4xnoodle ,
Our production use case is that we use multiple named cloud configs. Similar to what is described in the generic config doc: https://bosh.io/docs/configs/ . In our case not all of those cloud configs specify a network section.
Therefore, your second point will cover our use case.
Thanks!

**Comment by BeckerMax** [comment] 2020-02-21 13:55
We tested it with the the provided fix and the error still appears. 
We are working on a contribution to fix it.

New stacktrace:
```
/var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/validation_helper.rb:16:in `safe_property': Required property 'networks' was not specified in object ({"disk_types"=>[{"disk_size"=>120000, "name"=>"test"}]}) (Bosh::Director::
ValidationMissingField)
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:48:in `parse_networks'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/cloud_manifest_parser.rb:14:in `parse'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:127:in `block in populate_network_metrics'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:126:in `map'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:126:in `populate_network_metrics'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:105:in `populate_metrics'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/metrics_collector.rb:51:in `start'
        from /var/vcap/data/packages/director/ffdc857ce0b4db61d54446def6b79e1d050203c6/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/bin/bosh-director-metrics-server:26:in `<top (required)>'
        from /var/vcap/packages/director/bin/bosh-director-metrics-server:29:in `load'
        from /var/vcap/packages/director/bin/bosh-director-metrics-server:29:in `<main>'
```

**Comment by h4xnoodle** [comment] 2020-02-21 16:29
Does the metrics server still not start correctly?

I intended to keep the raise message in the logs, but the change should ignore it. The code that raises this message is correct (within the parser). For an individual cloud config, no networks doesn't make any sense. For metrics we'll just 'ignore'.

Is this an observation in the logs or still the cause of the server not starting? Can you provide your fixtures that get the metrics server to not start? Thanks for contributing.

**Comment by BeckerMax** [comment] 2020-02-24 16:13
Yes, the metrics server still failed to start. It failed because some of the cloud configs of in our test data were missing the networks _field_ completely and not only the value. 

While we saw that rescuing the ValidationMissingField would solve this issue we went for another solution:
On PR  [2243](https://github.com/cloudfoundry/bosh/pull/2243) we followed the `deploy` flow where the cloud configs first get consolidated before they are parsed. We implemented the same here.
Also we still throw an error if the consolidated cloud configs miss required fields or values. For us a release with these changes are sufficient.

As an additional resilience improvement we could not fail metric emition if the consolidated config is invalid. 

What do you think about it?

**Comment by h4xnoodle** [comment] 2020-02-24 16:44
Thanks for the fix -- looks good to me. Consolidating before parsing is a better way.

Merged in now, thanks!

**Closed by h4xnoodle** 2020-02-24 16:44 UTC
Labels: in progress
